# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaTree = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaTreeBranch1(dc.DataclassModel):
    left: GeneratedSchemaTree = dc.field("left")
    right: GeneratedSchemaTree = dc.field("right")

    __slots__ = ("left", "right",)


@typing.final
class GeneratedSchemaTree(dc.DataclassRootModel):
    root: (GeneratedSchemaTreeBranch1 | None) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaTreeBranch1", "GeneratedSchemaTree", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, left: typing.Any, right: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaTreeBranch1, GeneratedSchemaTree,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x9dQ\xbb\x12\xc2 \x10\xec\xf3\x15\x19\xb4\x8c\xa2)\xfd\x09\xed\x1d\x0b\x0c\x87\xc1A\x88\xc7Y8N\xfe]\x88&\x9216\x96\xfb\x98\xbd]xdy\xce\xe6\x12\x94g\x9b\xfc\x11@\x80\x84\x00\x03\x0a\xd8Y\xd8\xaa@\xec\xdfD>H\x9d\\9\xeb)\xc8\xf6f\xcc\xc0\xb7\xc5\xb4YH\xa9I;+\xcc\x0e]\x03H\x1a\xe2e%\x8c\x87"56\xa9\x9cF\x04\xcd\x80\xa2/6\xee@\x88=\xd9\x8cw\x8bx7ddj\x8bq\x12\xeaS\xfdoT\xf6#\x96!\\o\x1aA\x8e\x9e\xecS|\xb2B\xc2\x1dFato\xe2g0w<C\x95\xf8\xfa\xf3\x87\xacG]\x89\xe9\xe2/\xc5W5\\D\x14k\xa2\xc6o8?{g\x17/z\xe9\xf0\xc4%\x0aE\xbc\\\x95\xab\xc5\xba\xe4o\x7f\xd6>\x01^\xfe{\x9b', _namespace)
    dc.install_model(GeneratedSchemaTreeBranch1, _jsoncompat_init_1, b'x\xda\x9d\x91\xc1\x0e\x820\x10D\xef|ES=\x92\x90x\xf4\'\xf4n8 \xddjMm\xb1\x94\x83!\xfc\xbbm\x03\xa5\xb5\x88\x09\xc7\x9dY\xa6\xb3\x8f>C\x08\xef\x09\xd0\x16\x1fQo\x063j\x05\xe0\'3K\x01\'j\x84\xcb( o9\xbb\x96\xa2\xd5\xc6\x16\x1d\xe7^\x1f\xf2\xe5\xe5\x8a\x10\xa6\x99\x14\x15?+\xd9\x80\xd2\x0c\xec\xcb\xb4\xe2-\xe4\xe1b\x13\xdaa\x84\xf18P\x9d\xa8\xf6\x0e\x05\xb6\'\xde\x15\xee\xa2\xc2\x1d\x12-\x0dy\x9c\xa4\xd8\xed\xbe5*\xfb\x11\x8b\x15\xbc:\xa6\x80D\xc8\xe6\xe2\x8b\x15\x02\xad\x8c\xc2\xf4\xbb\xb1?\x03\xcb\xeb\x03\xea`oz\xbe\xcc\xa6\xc9\x95\xf8\x0b\x18?\x99\x88\x9c\x83S\x17p\x7fc^a2\xde\x9f\xe0\\\xfb\xc47Np\x85\x98f<\x0eK\x82c\xf8\x00W\xb8\xa2\xab', _namespace)
    dc.install_model(GeneratedSchemaTree, _jsoncompat_init_2, b'x\xda\x9dQA\x0e\xc2 \x10\xbc\xf3\x0a\x82\x1e\x9b\xf4\xee\'\xf4nz\xa8eQ\x0c\x81J\xe9\xc14\xfd\xbb@Z\x84\x96\xa6\xc6\xe3\xee\x0c\xc3\xec\xcc\x800&G\x0a\xac#\'<\xd8\xc1\x8eF\x03\x84\xc9\xceJ\xc2\x99\xd9\xc5uZ\xe0\x00y\xb8Q\xb23\x16\x96\xbd\x10a?\x16yrM)7\\\xc9Z\\\xb4jA\x1b\x0e\xeegV\x8b\x0e\x8a\x98\xd8\xc6p,a1\x01\xcc\xac\xb6\xee\x0e\x0d\xce\'9\x94\xfe\xa2\xd2\x1f\x92\x90\xc6"U\xd2\xfc\xfe\xf8W\x0am\xc8\x12\x0d\xaf\x9ek\xa0Id_\xe3Y\x0b\xd1\xaeJ\xc4\xcc\xbbue\x10u{B\x13\xf1\xe6\xef+4O\xde\xc4\xa2\xac\xd0\xe1\xaa\xa4\xc9r \xfcR\xccV)\xb9Bv\x12\x8c\x12\xcb\x96\xb0\xf7\x1c-d\xf2\xa1/\x03O\xc3\x0eAgCv_Th\xfc\x00u\xc2\xb0c', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaTreeBranch1, 3), (GeneratedSchemaTree, 1)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"one":[2,3]}]},{"types":null,"choices":[null],"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["left",4],["right",5]],"patterns":[],"required":["left","right"],"additional":6}}]},{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('root', GeneratedSchemaTree, 2, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"one":[1,2]}]},{"types":null,"choices":[null],"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["left",3],["right",9]],"patterns":[],"required":["left","right"],"additional":8}}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":[{"one":[1,5]}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["left",6],["right",7]],"patterns":[],"required":["left","right"],"additional":8}}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":["false"]},{"types":null,"choices":null,"rules":[{"ref":4}]}],"patterns":[]}'),
        ('union', (3, 4,), None, None),
        ('model', GeneratedSchemaTreeBranch1, (("left", "left", 1, False), ("right", "right", 1, False),), None, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["left",1],["right",8]],"patterns":[],"required":["left","right"],"additional":7}},{"object_length":{"min":2,"max":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"one":[3,4]}]},{"types":null,"choices":[null],"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["left",5],["right",6]],"patterns":[],"required":["left","right"],"additional":7}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":["false"]},{"types":null,"choices":null,"rules":[{"ref":2}]}],"patterns":[]}'),
        ("null",)
    ], b'{"version":2,"base_nodes":5,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,false,false],"json_keys":[[3,["\\"left\\":","\\"right\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaTreeBranch1, GeneratedSchemaTree,), globals())
