# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaE\x8c1\x0e\x800\x08E\xf7\x9e\x82\xa0\xa3\x89{o\xe3@\xb5\x89ACq0M\xef.\xb0\xb8\xf1>\xff\xbf\x9e\x00\x90\xceF\x98\xa1\xdbm4\x0b\x15#\x9cV\xbe\x14-\x1b\x8b\x97\xaa\x87*\x0f\x05\xf9+C\xd9l\x19\xac\x07\xf1\xaf\xd0\xf7v!6\x95\xca{8\xd2\xf8\x00\x83k\x1b#', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"not":1},{"if":{"condition":2,"then_node":3,"else_node":4}}]},{"types":null,"choices":null,"rules":["false"]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"ref":1}]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":1,"base_nodes":2,"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
