# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: dc.JsonValue = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda-\x8c\xcb\x0a\x80 \x10E\xf7}\x85H\xcbj\xcae\xbf\x12-,\xa7\x17\xa4\xa5\x06\x81\xf8\xefM\xd6f\x98s\xb8\xf7\x86\x8c1\x9e\xbbq\xc1]\xf2\x96\xf1\xc5\xfb\xc3\xb5\x00\x9b3\xba\xfcte\xec\x0c\xca\xca\xc9\x83\xa8E]6\x02\xfe|\xf1\x96\x15\x1e\xa8\x15\xeaqEG\x0b\x81\x1c\xd9\xf3\xban\xa2.\x11\xf1dL\x8a\'\x18\xa4\xe5\xe9\xef\xe9\xc6,>I-#\xfb', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"dependencies":[["quux",["foo","bar"]]]}]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":1,"base_nodes":2,"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
