# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x8d\x8e\xbd\x0e\xc20\x0c\x84\xf7<E\x141\xb6\xa4d\xec\xdb\x84\xc6\xfdA"\xb6\x1c/\xa8\xca\xbb\x93\x00*\x1d:t\xb1u\x9f\xef\xac[\x95\xd6\xe6\x92\x86\x19\x9e\xde\xf4\xda\xcc"\x94zk\x1f\x09c\xfb\xc5W\xe4\xc9\x06\xf6\xa3X\xd7\xb9\xae\xbd9\xfb\xf375\x1c\x80 \x06\x88\xc3\x02\xa9|X\x0b+\xf4\xeey\x13E\x12#\x01\xcb\xder`\xfb y\x11\xd4&K\x14\x98\x80\xcdv\xcb\xcd?7"\x9e\xcf\xa9\xfd\xae3\xab\xfc\x06\xe7\xa4>\x04', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, b'x\xda\x8d\x8e1\x0e\x80 \x10\x04{^A\xae\xb6\xb0\xf6\x15~Aa5\x98\x08\x04i\x0c\xe1\xef"F\xc4\xc4\xc2\xe6.7\xb7\xbb\xd9\xc08\'\x09\x0b-\xa1\x85\xc2F\x1d\x0f\x89%:\x0e\xae\x1c\xe9\xb4\xceX8_K>d\x19\xf9\xdd"1R\xdac\x86\xa3\xf2\x8b\xcd\xe3\x9b\x8c\xf9\xefc\xf5>gN\xa2U\xe9\xbe\xae\xd5f\xfanz)\xefh3.\x10\x9eX<\x00\x84\xc0=\xba', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"dependent_schemas":[["bar",1]]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2],["foo",2]],"patterns":[],"required":[],"additional":null}}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (2, 4, 6, 7, 8, 9, 10,), None, None),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":3,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"dependent_schemas":[["bar",1]]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2],["foo",2]],"patterns":[],"required":[],"additional":null}}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ('list', 5),
        ('root', GeneratedSchemaItem, 3, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":4,"base_nodes":11,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,false,false,true,false,false,false,false,false],"json_keys":[[2,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,), globals())
