# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: dc.JsonValue = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaM\x8b;\x0e\x80 \x10\x05{N\xb1!\x96\xe0"%\x97\xf0\x00\xc6\x82(H\x8c\x82\x01\xac\x8cw\x17?\x85\xdd\xbc\x97\x99\x83\x00\xd0*\x0d\xce\xac\x9a*\xa0.\xe7-)\xc49\x05\xcf\xdf\xbb\x0eq\xc21j\x9bQ\x0a)x#\xf1\xf3\xd9\x1d\x07oZ[\xd2\xae\x0c\x80\x1cw\xc3\x1e\xb2zI\x7f,\xd4\x93\xf3\x02V\xe8\x1f\x99', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"one":[1,2,2]}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":3,"base_nodes":2,"guard_nodes":[],"guards":[],"conversion_validates":[true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
