# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x9dO1\x0e\x830\x0c\xdcyE\x14u\x84\x86f\xe4\x13}@\xc5\x10\xc0)E*\xa6\x8e;\xb4\x88\xbf7\xb8\x11\x03#\xcbYw\xf6\x9d|s\xa6\x94>\x85\xb6\x87\xa7\xd3\x95\xd2=\xf3\x14*c\x86\x80c\xf1\x97\xcfHw\xd3\x91\xf3lli\xcb\xe2bM\xba\xcfW3\x8ep\xf5\xd1z\x8bD\xa9Y0\xca\x04\xaf\xf7\x83\xa0\xdb6\xa2zDq%\xda8\xd2\x89\xd52\x97\xfcP\xcaw\x97\x12\xb1\x96\xe7\xf83\xc1Z\x0b\x9b\x01Z\xd6\xd9\xf2\x03\xb4\xff8\xc2', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('model', GeneratedSchema, (), 1, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"one":[1,2]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":["foo","bar"],"additional":null}}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":["foo","baz"],"additional":null}}]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":1,"base_nodes":2,"guards":[],"conversion_validates":[false,false],"json_keys":[[0,[]]]}')


_jsoncompat_bind((GeneratedSchema,), globals())
