# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | GeneratedSchemaBranch22 | collections.abc.Sequence[GeneratedSchemaItem2] | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2Bar(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2Baz(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    bar: GeneratedSchemaBranch2Bar = dc.field("bar")
    baz: dc.Omittable[GeneratedSchemaBranch2Baz] = dc.field("baz", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("bar", "baz", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch22Foo(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch22(dc.DataclassAdditionalModel["typing.Any"]):
    foo: GeneratedSchemaBranch22Foo = dc.field("foo")
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem2(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2Bar", "GeneratedSchemaBranch2Baz", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "GeneratedSchemaBranch22Foo", "GeneratedSchemaBranch22", "GeneratedSchemaItem2", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, bar: typing.Any, baz: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_6(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_7(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2Bar, GeneratedSchemaBranch2Baz, GeneratedSchemaBranch2, GeneratedSchemaItem, GeneratedSchemaBranch22Foo, GeneratedSchemaBranch22, GeneratedSchemaItem2,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x95\x8d1\x0e\xc20\x0cE\xf7\x9c"\x8a\x18[R2\xf6\x12\x1c\x001\x04\xea\xd0"Q\x07\']\xa8zw\x1cH\xab2\xa1.\x96\xff\xfb\xfe\xfe\xa3\x90R\xed\xc2\xb5\x85\x87U\xb5Tm\x8c>\xd4Z\xdf\x03\xf6\xe5\x17\xef\x91n\xba!\xeb\xa26\x95\xa9\xca\x83\xd1\xf9\xbeHa\xec\xe1\xe88zb!\xe5\xf8\x99\x8c=\xa1\x07\x8a\x1d\x04\xf6f\xca\xfcb\x89A\xa4\x01\x8a5|e\x98\xd94\x9b\x8a\xe09t\x04\xcd\xd2\xb0|\xc9\xea,V\x81\xbf\xf5\x0eq[S\x0a\xfc6\x89\xb4Mom\x99K\x1c', _namespace)
    dc.install_model(GeneratedSchemaBranch2Bar, _jsoncompat_init_1, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBranch2Baz, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_3, b'x\xdaM\xcb\xb1\x0e\x80 \x0c\x04\xd0\x9d\xaf \x9dY\\\xfd\x0aw\xe3 \xda\x01\x13\x05k\x19\x94\xf0\xefV\xa2\x91\xed\xee].)\xadau[G> \xb1\xc3\x03Z\xdd\x98GCMID\xcc\x8e$\x85)\xa2\xf9\xe0zAz.?\xc2=:\xc2Y\xbc\xff_\x92\x862\xf3\x19P&\xf0v\xc1\x89A\xe5\x1b|\xe7#\xa9', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_4, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBranch22Foo, _jsoncompat_init_5, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBranch22, _jsoncompat_init_6, b'x\xdaM\xca1\x0e\x800\x0c\x03\xc0\xbd\xaf\xa82\xb3\xb0\xf2\x0av\xc4\x02\x04\xa9H\x90\x12\xd2\x01U\xfd;\xa6\x0bl\xf6\xd9\xd9yO{8z\x95\xc8j\x81/\xea|\xdb\xbc\x1a\xff\x94!\xb0U\x04\xc541z\xa97\xe53\x05\xe5\x05>|\'\xa4\xb1\xcevG\xc6D2m<\x1b\xb9\xf2\x00MB\x1fv', _namespace)
    dc.install_model(GeneratedSchemaItem2, _jsoncompat_init_7, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2Bar, 3), (GeneratedSchemaBranch2Baz, 5), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 11), (GeneratedSchemaBranch22Foo, 7), (GeneratedSchemaBranch22, 6), (GeneratedSchemaItem2, 9)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"one":[1,3]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2],["baz",2]],"patterns":[],"required":["bar"],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",2]],"patterns":[],"required":["foo"],"additional":null}}]}],"patterns":[]}'),
        ('union', (2, 6, 8, 10, 12, 13, 14, 15, 16,), None, None),
        ('model', GeneratedSchemaBranch2, (("bar", "bar", 3, False), ("baz", "baz", 5, True),), 4, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["bar",1],["baz",1]],"patterns":[],"required":["bar"],"additional":null}},{"object_length":{"min":1,"max":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaBranch2Bar, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ('root', GeneratedSchemaBranch2Baz, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('model', GeneratedSchemaBranch22, (("foo", "foo", 7, False),), 4, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["foo",1]],"patterns":[],"required":["foo"],"additional":null}},{"object_length":{"min":1,"max":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaBranch22Foo, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('list', 9),
        ('root', GeneratedSchemaItem2, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('list', 11),
        ('root', GeneratedSchemaItem, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":3,"base_nodes":17,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,true,true,false,true,true,true,false,true,false,true,false,false,false,false,false],"json_keys":[[2,["\\"bar\\":","\\"baz\\":"]],[6,["\\"foo\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2Bar, GeneratedSchemaBranch2Baz, GeneratedSchemaBranch2, GeneratedSchemaItem, GeneratedSchemaBranch22Foo, GeneratedSchemaBranch22, GeneratedSchemaItem2,), globals())
