# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch0 | GeneratedSchemaBranch1) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch0(dc.DataclassModel):
    kind: typing.Literal["int"] = dc.field("kind")
    value: int = dc.field("value")

    __slots__ = ("kind", "value",)


@typing.final
class GeneratedSchemaBranch1(dc.DataclassModel):
    kind: typing.Literal["str"] = dc.field("kind")
    value: str = dc.field("value")

    __slots__ = ("kind", "value",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch0", "GeneratedSchemaBranch1", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, kind: typing.Any, value: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, kind: typing.Any, value: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch0, GeneratedSchemaBranch1,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\xbd\x90\xcb\x0e\x820\x10E\xf7|E\xd3\xb8D\xab,\xf9\x09\xdd\x1b\x16\x95\x0eP\xc4\x16\xdb\xc1\xc4\x10\xfe\xdd\xa2\xe5!\xee\\\xb0\x99d\xee\xcc\x99\xc7m\x03B\xe8\xc6\xa6\x05\xdc8\x8d\x09-\x10k\x1b3VZ\xad\xb6\x1fy\xa7M\xce\x84\xe1\x19\xb2h\x1f\xed\xb7\x87\x88\xf9\xfe\xb0\x87\xb5\x82c\xe6\xd0\xb3K\x08i\xdf\xd1\xc9\\\x08\x89R+^\x9d\x8c\xae\xc1\xa0\x04\xeb\xba2^Y\x08\x87\xa6z^\x1aP\xa7_\xa5\x12_\x8a\xd3R\xad,\xf6\'J\x85t,t\xe1D=x\xd5\xc0\x12\xc3g\x0d\x9e\x82\x1c\xcc\x8c\x0c\x16\x13\xa8\x81{#\x0d\x88\xf1\x99\xe9\x96\x9f->OFx\xd8\xa3/%\xa4\xfe@?z\x05O,\x9a?<q\x94T\xf9\xba\x96\xb8\x98\x04\xdd\x0b\xc1\xda\x98 ', _namespace)
    dc.install_model(GeneratedSchemaBranch0, _jsoncompat_init_1, b'x\xdaU\x8e\xbb\x0e\xc20\x0cE\xf7~E\x959\x0b\x8c\xfc\x04\xec\xa8C .2\xe4E\x9a \xa1*\xff^\xe7\xd1\xaa\x9d\xec{|}\xed\xb9\xeb{&\xa4\xc4\x80\xd6\x08u\xf3\xd6\x81\x0f\x08\x13\xbb\xf4\xa3P\x13\xf0l\xd0h\x0e\x93s\xa1n\x8ff"\xc4>h\xe4\xa6H\x83\x89\x9a\xf4\xbdi"h\x02kj(5\xf1\xba\xfa\x13*\xc2~WG\x15\xd0)\xb8\x8eDO|\xc5\xe1\xef\xb2-\x07\xc1\x0b|\x0dK]\x0bb\x1e\xbe\x11=\xc8\xedj\xfd\xe9p\x84\xfa\xa1\x98\xd7,\xfbx\xc3\x93\xfeJ\x0b\x87\xefF\xe6', _namespace)
    dc.install_model(GeneratedSchemaBranch1, _jsoncompat_init_2, b'x\xdaU\x8e;\x0e\xc20\x10D\xfb\x9c"r\xed\x02Qr\x06\x0az\x94\xc2\xe0%,8\xb6\xf1\x07\x09E\xbe;\xebO\xa2\xa4\xb2\xe7\xed\xec\xcc\xce]\xdf3!%\x064Z\xa8\x8b3\x16\\@\xf0\xec\xd4?\x84\xf2\xc0\xb3aB\xbd\x9b\x1c\x0b\xb5[4\x13!\xf6F-WE\x1at\x9cH_\x9b&\xe2\x83cM\x0d\xe5M\xbc\xae~\x85\x8a\xb0\xdd\xa5\xd63\xe81<\x09\x1e\xf8B\xc3\xcffW\xceA=\xd6\xa8\xd4\xb5\x18\xe6\xe0\x13\xd1\x81\\;\xebE\xbb\x0a\xfa\x0f\xc5\xbcD\x99\xdb\x0b\xee\x81u\xe9\x0f\xe1\x9eF!', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch0, 2), (GeneratedSchemaBranch1, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"one":[1,5]}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["kind",2],["value",3]],"patterns":[],"required":["kind","value"],"additional":4}}]},{"types":null,"choices":["int"],"rules":[]},{"types":["integer"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["kind",6],["value",7]],"patterns":[],"required":["kind","value"],"additional":4}}]},{"types":null,"choices":["str"],"rules":[]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (2, 5,), "kind", (("int", 0), ("str", 1),)),
        ('model', GeneratedSchemaBranch0, (("kind", "kind", 3, False), ("value", "value", 4, False),), None, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["kind",1],["value",2]],"patterns":[],"required":["kind","value"],"additional":3}},{"object_length":{"min":2,"max":null}}]},{"types":null,"choices":["int"],"rules":[]},{"types":["integer"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('literal', ("int",)),
        ("int",),
        ('model', GeneratedSchemaBranch1, (("kind", "kind", 6, False), ("value", "value", 7, False),), None, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["kind",1],["value",2]],"patterns":[],"required":["kind","value"],"additional":3}},{"object_length":{"min":2,"max":null}}]},{"types":null,"choices":["str"],"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('literal', ("str",)),
        ("str",)
    ], b'{"version":3,"base_nodes":8,"guard_nodes":[],"guards":[],"conversion_validates":[true,false,true,false,false,true,false,false],"json_keys":[[2,["\\"kind\\":","\\"value\\":"]],[5,["\\"kind\\":","\\"value\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch0, GeneratedSchemaBranch1,), globals())
