# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    foo_bar: dc.Omittable[float] = dc.field("foo\tbar", default=dc.JSONCOMPAT_MISSING)
    foo_bar2: dc.Omittable[float] = dc.field("foo\nbar", default=dc.JSONCOMPAT_MISSING)
    foo_bar3: dc.Omittable[float] = dc.field("foo\fbar", default=dc.JSONCOMPAT_MISSING)
    foo_bar4: dc.Omittable[float] = dc.field("foo\rbar", default=dc.JSONCOMPAT_MISSING)
    foo_bar5: dc.Omittable[float] = dc.field("foo\"bar", default=dc.JSONCOMPAT_MISSING)
    foo_bar6: dc.Omittable[float] = dc.field("foo\\bar", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo_bar", "foo_bar2", "foo_bar3", "foo_bar4", "foo_bar5", "foo_bar6", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, foo_bar: typing.Any = dc.JSONCOMPAT_MISSING, foo_bar2: typing.Any = dc.JSONCOMPAT_MISSING, foo_bar3: typing.Any = dc.JSONCOMPAT_MISSING, foo_bar4: typing.Any = dc.JSONCOMPAT_MISSING, foo_bar5: typing.Any = dc.JSONCOMPAT_MISSING, foo_bar6: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"properties\": {\n    \"foo\\tbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\nbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\fbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\rbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\\"bar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\\\bar\": {\n      \"type\": \"number\"\n    }\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo\\tbar",1],["foo\\nbar",2],["foo\\fbar",3],["foo\\rbar",4],["foo\\"bar",5],["foo\\\\bar",6]],"patterns":[],"required":[],"additional":null}}]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"minProperties\": 0,\n  \"properties\": {\n    \"foo\\tbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\nbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\fbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\rbar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\\"bar\": {\n      \"type\": \"number\"\n    },\n    \"foo\\\\bar\": {\n      \"type\": \"number\"\n    }\n  },\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["foo\\tbar",1],["foo\\nbar",2],["foo\\fbar",3],["foo\\rbar",4],["foo\\"bar",5],["foo\\\\bar",6]],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]},{"types":["number"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_2, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 6)], [
        ('root', GeneratedSchema, 1),
        ('union', (2, 5, 3, 7, 8, 9, 10,), None, None),
        ('model', GeneratedSchemaBranch2, (("foo\tbar", "foo_bar", 3, True), ("foo\nbar", "foo_bar2", 3, True), ("foo\fbar", "foo_bar3", 3, True), ("foo\rbar", "foo_bar4", 3, True), ("foo\"bar", "foo_bar5", 3, True), ("foo\\bar", "foo_bar6", 3, True),), 4),
        ("float",),
        ("any",),
        ('list', 6),
        ('root', GeneratedSchemaItem, 4),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":1,"base_nodes":11,"guards":[],"conversion_validates":[false,false,false,false,false,false,true,false,false,false,false],"json_keys":[[2,["\\"foo\\\\tbar\\":","\\"foo\\\\nbar\\":","\\"foo\\\\fbar\\":","\\"foo\\\\rbar\\":","\\"foo\\\\\\"bar\\":","\\"foo\\\\\\\\bar\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,), globals())
