# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassModel):
    id: str = dc.field("id")
    name: str = dc.field("name")
    nested: dc.Omittable[GeneratedSchemaNested] = dc.field("nested", default=dc.JSONCOMPAT_MISSING)
    tags: dc.Omittable[collections.abc.Sequence[str]] = dc.field("tags", default=dc.JSONCOMPAT_MISSING)

    __slots__ = ("id", "name", "nested", "tags",)


@typing.final
class GeneratedSchemaNested(dc.DataclassModel):
    count: dc.Omittable[int] = dc.field("count", default=dc.JSONCOMPAT_MISSING)
    flag: (typing.Literal[False] | typing.Literal[True]) = dc.field("flag")

    __slots__ = ("count", "flag",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaNested", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, id: typing.Any, name: typing.Any, nested: typing.Any = _jsoncompat_missing, tags: typing.Any = _jsoncompat_missing) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, count: typing.Any = _jsoncompat_missing, flag: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaNested,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x8d\x91An\xc3 \x10E\xf7>\x85\x85\xbat\x8a\xebeN\xd1}\xd5\xc5\xc4\x1e\x13"\x03.\x8c\x17Q\xe4\xbb\x17\x13\x9c`\x12)\xd9\xc1\xe3\xcf\xe7\xcf\xcc\xa5(K\xf6\xe1\xda#*`\xfb\x92\x1d\x89F\xb7\xe7\xfc\xe4\x8c\xde]\xf1\xa7\xb1\x82w\x16z\xe2M\xdd\xd4\xbb\xaf\x86G}\xb5\x14C\xd7I\x92F\xc3\xf0m\xcd\x88\x96$:\xef\xd4\xc3\xe00\x08\xc6\x14_<\xf1Lv\xb7\xb3\xbf\xd1y\xc4\xe5sGVj\xc1\x02\x9e\xab\xabR\x83\xc2\xb7\xb5\xe8\x087\xce\xaf\xc2\x05\xd1\x93\x80\x81\xb7f\xd2\xb4A\x1e*\xa9\xa5\x9a\x94\xc7u\x95\xf25\x97\xd4\x84\x02-\xbb\xbd\xcdw\x19\xeb\x07\x10\xb9\xe1Zx0f@\xd0Ia\x91\x190\x8b\x7f\x93\xb4\xa1\xc3\x9f\xcc4^\x7f\xab|N\xe6p\xc2\x96\xb6s"\x10i\xabL\x12\xaa\xac\xf7gcN\xa3\xac\xef`-\x9c\xa3{\x11\x05\x8f9\x97}\xa7\xfb,b\xd2\x87\x94\xf3?\x86\x89\xa5\x1f', _namespace)
    dc.install_model(GeneratedSchemaNested, _jsoncompat_init_1, b'x\xdaU\x8e\xbb\x0e\xc20\x0cE\xf7~E\xe4\xb9\x03\xac\xfc\x04\xec\xa8Ch\x9d\xca(/Rg@U\xff\x9d\x90\xa4\xa1d\xca=\xd7>\xf2\xda\x09\x01r\x9a\x88\xc9Y\xa9o\xc1y\x0cL\xb8\xc0E(\xa9\x17\xec\xbf\x03\x86\xec_s\xce\xd4\x1f\xd1\x9aHb\xa3\x8b\x96[,\xabd\xa2I\xe8\xd47\x165\x93\xd7xU\xbb+c~{L\x00\xc82\xce\x18 \xf3\xad\xd4\xa0\xb4\x9c\x8f^\xb4Yz\xafY\xfc\xae-\x8fC\xc4\x1a\x86"\xea\xaa\x0c\x02\xbe"\x05\x9c\xdaz\x91\xa7\xef\x90\xfb\xfd\x0e\xf7x\xe2\xc8\xd0m\x1f}*K\xf4', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaNested, 2)], [
        ('model', GeneratedSchema, (("id", "id", 1, False), ("name", "name", 1, False), ("nested", "nested", 2, True), ("tags", "tags", 7, True),), None, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["id",1],["name",1],["nested",2],["tags",6]],"patterns":[],"required":["id","name"],"additional":5}}]},{"types":["string"],"choices":null,"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["count",3],["flag",4]],"patterns":[],"required":["flag"],"additional":5}}]},{"types":["integer"],"choices":null,"rules":[{"bound":{"value":0,"lower":true,"exclusive":false}}]},{"types":["boolean"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":1}}]}],"patterns":[]}'),
        ("str",),
        ('model', GeneratedSchemaNested, (("count", "count", 3, True), ("flag", "flag", 4, False),), None, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["count",1],["flag",2]],"patterns":[],"required":["flag"],"additional":3}},{"object_length":{"min":1,"max":null}}]},{"types":["integer"],"choices":null,"rules":[{"bound":{"value":0,"lower":true,"exclusive":false}}]},{"types":null,"choices":[false,true],"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("int",),
        ('literal', (False, True,)),
        ('literal', (False,)),
        ('literal', (True,)),
        ('list', 1)
    ], b'{"version":3,"base_nodes":8,"guard_nodes":[{"original":3,"guard":{"types":["integer"],"choices":null,"rules":[{"bound":{"value":0,"lower":true,"exclusive":false}}]}}],"guards":[{"owner":2,"field":0,"guard":0}],"conversion_validates":[true,false,true,false,false,false,false,false,false],"json_keys":[[0,["\\"id\\":","\\"name\\":","\\"nested\\":","\\"tags\\":"]],[2,["\\"count\\":","\\"flag\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaNested,), globals())
