# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: float = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda-\xcbM\x0a\x80 \x10@\xe1\xbd\xa7\x90\xa1e6\xe6\xd2\xdbXY\x12\xf8\x833-"\xba{Hn\x1f\xef{\x84\x940\xd0\x1a|t`%\x04\xe6B\x16\xf1\xa4\x9c\xd4\x9f\xa7\\\x0f\xdc\xaa\xdb\x19\x8d6Z\xcd\x06\xfb?6\xccw\xf1M\xa6+.\xbe\x82x?1\xd6\x19c', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":["number"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("float",)
    ], b'{"version":4,"base_nodes":2,"guard_nodes":[],"guards":[],"conversion_validates":[true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
