# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaItem", "GeneratedSchemaBranch2", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaItem, GeneratedSchemaBranch2,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda5\x8b;\x0e\x80 \x10D{OA\x88\xa5\xbaJ\xe9U\x8c\x05*j\x08\x02\x81\xb5 \xc6\xbb\xbb\xfe\xbay3\xf3\x8e\x8c1\x9e\xc7qU\x9b\xe4-\xe3+\xa2\x8f-\x80\x8e\xce\x96o]\xb9\xb0\xc0\x14\xe4\x8c jQ\x97\x8d\x80\xef_\xdc2&\xaf\xc8\xec(\x13\xc9\x10dz\x06\x027h5\xe2Ov7\x86S\xec\xb3\xf3\x02\x12\xe8 \xab', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_1, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_2, b'x\xdaM\xc8;\x0e\x00\x10\x0c\x00\xd0\xdd)\x9a\xce\x06\xb3S8\x03\xe9@\x82\x86."\xee\xee3\x19\xdf\x9b\x0a\x00s,\xaeU\xa6&\x91:Z0\xfa.\xff5\xd7;\x19LGX}\xa2 \xa8\xd6\x06}$\x13v', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaItem, 5), (GeneratedSchemaBranch2, 2)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":["array","object","null"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (2, 4, 6,), None, None),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}}]}],"patterns":[]}'),
        ("any",),
        ('list', 5),
        ('root', GeneratedSchemaItem, 3, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("null",)
    ], b'{"version":3,"base_nodes":7,"guard_nodes":[],"guards":[],"conversion_validates":[true,false,true,false,false,true,false],"json_keys":[[2,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaItem, GeneratedSchemaBranch2,), globals())
