# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassRootModel):
    root: (GeneratedSchemaN1 | GeneratedSchemaN3) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: GeneratedSchemaN2 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: str = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN4(dc.DataclassRootModel):
    root: str = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "GeneratedSchemaN4", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\xadRK\x0e\xc2 \x10\xdd{\x8af\xecRE\xab\xab^\xc2\x03\x18\xd3\x90B-\x86\x82\x01\\\xb4M\xefn\x0b\x88\xf8Y\x99n\x80y\xf3{\xf3\x98~\x91$\x90\x12Zi\xc8\x93~4F\x93\x91\x82\x89\x82\x8a{\x13\xb0\x11\xf5\xf6\xc9\xdbI\xf0Xo\xca\xc8\xe8\x84\xda\x98\x9b\xce\x11\xe2\xb2\xc4\xbc\x96\xda\xe4\xbbl\x7f@D\xe1\xcad\xdbl\xbb\xdee\x88\x11\xd4\xb4\x05#T\x18V1\xaa6W-\x05\xac\xe2j\xa6\xbd\xd1\xa9\x9c\xb8s\x0e\xc11\xf8\xd7\xd9\xde\x83\xcb\x00E1/\x1ce]\xd6\xb4\xc11\xe9\xd9h\x05J\xda(&.\xf0F\xa1\xeb:\xcf\xa0\x94B\x9b\x98\xc0\'0\xafT?\x85r2M\xa7\xe5\x07i\x90%\xf4\x9c\xca\xac\x1d\xbc\x91\xea\xe2\x9a\xa2gW\x1fo\x93\xb1h\x8fU\xf8\xf6\x97\xae\x8aN(,\x91\xdd\x1d\x14\xadL\xac\xccW\xfc\xffC\x87\xa1\xce\x8b\xe1\x01\xec9\xbc\x0e', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\xa5RK\x0e\x820\x10\xdds\x0aR]\xa2\x85\xc2\x8a3\x98x\x00c\x0c\xb1\x05j`0mY\x10\xc2\xdd-R\xb0\x90\x80&\xee\xe6\xf3\xde\xeb\x9b\xe9\xb4\x8e\xeb\xa2=e\xa9D\xb1\xdb\xeaD\xa7\xe0Oq\xdf\x94\xf7\x9c\x95\x89.\xa1\\\xa9\xa7\x8c1~\xc8\x0a\x0eC\xf9X\x89\x0cS\x91\xa4\x0a\x13\x9f\xf8\x87\x80`\x83\xf7F\x81\x04\x9as\xaa\xe9\x17Sp\'\xedA_\xb0\xbe\x8bv\xf8m\x03C\x80\xa6v\xe7\xfd\xc8\x09-\x8e\x89\xae\x8e\xa5\x80\xb4\xaa=\xd3\x92O\xd0\x1cMl4\x83\xba\xdc\xf0\xcf\xa9\xbd\x9b\xa2\xba\'E^I\x15\x07$\x8c\x86\xd5\x8c\x9b\xe1\x14\x97\xcd\x8dS\x06\x8a\xa7\x9c\x89c\xbfH\xe4\xd9j\xaay\xb2^\x0e\xea\xa2\xf8:S\xb89S\xb4\x98)\xb2\xd1%\x87\x13\x83L\xe5\xba\xe8O_5\xbe.\x95\xe0\x90\x19\xbec4\xfe\xba\x84\xc5\x15\xac\xbb\x0ef\xae\xd7q\xe1\xc7\xdd\xd5\xe9^\x8b=\xa4V', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda\x8dQK\x0e\x820\x14\xdcs\x0aR]\x02\x85\xc2\x8a3\x98x\x00c\x0c\xa1\x05j\xe0A\xda\xb2 \x84\xbb[\xa4\x90J\x0c\xba{\x9f\x99\xe9\x9b\xe9\xe8\xb8.:SVH\x94\xba\xa3nt\x0b\xe1V\xcfK\x99W\xac\xc9\xf4\x08UJu2\xc5\xf8)[\xf0\x97q\xd0\x8a\x12S\x91\x15\x0a\x93\x90\x84~D\xb0\xc1{\xab@\x06\xc3\xb5\xd0\xf4\x9b\x19\xb8\x9b\xf6\xa2/\xd8\xbcE\'\xfc>\x03C\x84\xb6\xf5\xe4\xfd\xc9\x89-\x8e\xa9\xee\x8e\xa5\x80\xb4\xaa\xedi\xcf\'\xe8\x13Ml4\x83\xbe9\xb8\x9fS;\x9b\xba\xcd\xb3\xbaj\xa5J#\x12\'K4k2\x9c\xe2fxp\xca@\xf1\x823\x11\xccA"\xcfVSC\xc7f9\xe8\xeb\xfa\xa7\xa7\xf8\xd0S\xb2\xf3\x94\xd8\xe8\x86\xc3\x85A\xa9*=\x0c\xb7\xafZ_\x97Jp(\x0d\xdf1\x1a_S\x9b^\x02\x9b\x82\xce', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xda5\x8c1\x0a\x840\x10\x00{_\xb1,W\xde\xddj\xb4\xcaWDDL\xc4\x95\x98\x88Y\x0b\x11\xffn\x14l\x86a\x8a92\x00\xb4~\x9bQC\x9d\x1c\xe0x\x98\xea\x87M\x8a8\x8a,Q\x13\xb9\xd0wn\x0cQt\xa1\xca\x8a\xcc\xda\x0d\xa2r\x95\xff\x0aElh\xde[6\xd6\x0b\x0fl\xd7\xff\x14\x83\xc7\xef{\x92}\xb1\xf7\xcao\xce\xe1\x13\xcf\xc4&;/g\x09"G', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda\x8dQA\x0e\x820\x10\xbc\xf3\x0aR=\x02\x85\xc2\x897\x98\xf8\x00c\x0c\xa1\x05j`!m9\x10\xc2\xdf-RH%\x06\xbduwgfw\xa6\xa3\xe3\xba\xe8LY!Q\xea\x8e\xba\xd0%\x84\xdb{\x1e\xca\xbcbM\xa6[\xa8R\xaa\x93)\xc6O\xd9\x82\xbf\xb4\x83V\x94\x98\x8a\xacP\x98\x84$\xf4#\x82\x0d\xde[\x052\x18\xae\x85\xa6\xdfL\xc3\xdd\xb4\x17}\xc1\xe6):\xe1\xf7\x19\x18"\xb4\x8d\'\xefONlq\xcc\xeb\xeeX\x0aH\xab\xda\x9e\xf6|\x82>\xd1\xc4F3\xe8\x9b\x83\xfb9\xb5\xb3\xa9\xdb<\xab\xabV\xaa4"q\xb2D\xb3&\xc3)n\x86\x07\xa7\x0c\x14/8\x13\xc1\x1c$\xf2l55tl\x96\x83\xbe\xae\x7fz\x8a\x0f=%;O\x89\x8dn8\\\x18\x94\xaa\xd2\xcdp\xfb\xaau\xbbT\x82Ci\xf8\x8e\xd1\xf8\xbaaz\x01\x02\xa3\x82\xd0', _namespace)
    dc.install_model(GeneratedSchemaN4, _jsoncompat_init_5, b'x\xda\xab\xe6RPP\xca\xcd\xcc\xf3I\xcdK/\xc9P\xb2R0\xd0\x01\x89\x94T\x16\xa4\x029J\xc5%E\x99y\xe9J\\\xb5\x00\xe4\xcb\x0br', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 3), (GeneratedSchemaN2, 4), (GeneratedSchemaN3, 6), (GeneratedSchemaN4, 8)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"any":[2,5]}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":[{"$id":"https://localhost:1234/draft2020-12/id/my_identifier.json","type":"null"}],"rules":[]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":null,"rules":[{"ref":7}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN0, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"any":[1,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":[{"$id":"https://localhost:1234/draft2020-12/id/my_identifier.json","type":"null"}],"rules":[]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (3, 6,), None, None),
        ('root', GeneratedSchemaN1, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":[{"$id":"https://localhost:1234/draft2020-12/id/my_identifier.json","type":"null"}],"rules":[]}],"patterns":[]}'),
        ('model', GeneratedSchemaN2, (), 5, b'{"version":2,"nodes":[{"types":null,"choices":[{"$id":"https://localhost:1234/draft2020-12/id/my_identifier.json","type":"null"}],"rules":[]}],"patterns":[]}'),
        ("any",),
        ('root', GeneratedSchemaN3, 7, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("str",),
        ('root', GeneratedSchemaN4, 7, b'{"version":2,"nodes":[{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}')
    ], b'{"version":3,"base_nodes":9,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,false,false,false,true,false,true],"json_keys":[[4,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,), globals())
