# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"allOf\": [\n    {\n      \"prefixItems\": [\n        {\n          \"minimum\": 3\n        }\n      ]\n    }\n  ],\n  \"items\": {\n    \"minimum\": 5\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1]},{"array":{"prefix":[],"items":3}}]},{"types":null,"choices":null,"rules":[{"array":{"prefix":[2],"items":null}}]},{"types":null,"choices":null,"rules":[{"bound":{"value":3,"lower":true,"exclusive":false}}]},{"types":null,"choices":null,"rules":[{"bound":{"value":5,"lower":true,"exclusive":false}}]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1),
        ("any",)
    ], b'{"version":1,"base_nodes":2,"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
