# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (typing.Literal["a"] | typing.Literal["b"]) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\xab\xe6RPPJ\xcd+\xcdU\xb2R\x88\x06\xb2\x81\xbcD%\x1d\x08#I\x09H\xc7r\xd5\x02\x00\x8e\x0b\x07-', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":["a","b"],"rules":[]}],"patterns":[]}'),
        ('literal', ("a", "b",)),
        ('literal', ("a",)),
        ('literal', ("b",))
    ], b'{"version":1,"base_nodes":4,"guards":[],"conversion_validates":[true,false,false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
