# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaName(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaName", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaName,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"Name\": {\n      \"allOf\": [\n        {\n          \"$ref\": \"#/$defs/Name\"\n        },\n        {\n          \"type\": \"string\"\n        }\n      ]\n    }\n  },\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"propertyNames\": {\n    \"$ref\": \"#/$defs/Name\"\n  },\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"property_names":1}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"all":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaName, _jsoncompat_init_1, "{\n  \"$defs\": {\n    \"Name\": {\n      \"allOf\": [\n        {\n          \"$ref\": \"#/$defs/Name\"\n        },\n        {\n          \"type\": \"string\"\n        }\n      ]\n    }\n  },\n  \"allOf\": [\n    {\n      \"$ref\": \"#/$defs/Name\"\n    },\n    {\n      \"type\": \"string\"\n    }\n  ]\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,5]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"all":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaName, 2)], [
        ('model', GeneratedSchema, (), 1),
        ("any",),
        ('root', GeneratedSchemaName, 1)
    ], b'{"version":1,"base_nodes":3,"guards":[],"conversion_validates":[false,false,false],"json_keys":[[0,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaName,), globals())
