# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassModel):
    value: dc.Omittable[GeneratedSchemaValue] = dc.field("value", default=dc.JSONCOMPAT_MISSING)

    __slots__ = ("value",)


@typing.final
class GeneratedSchemaValue(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaValue", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, value: typing.Any = dc.JSONCOMPAT_MISSING) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaValue,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda}PO\x0f\x82 \x14\xbf\xfb)\x1cy\xcc0\x8f~\x89:ui\x1dH@q\x06\x0c^m\xce\xf9\xdd\x03Ds\xadu\xe3\xf7\xef\xf1~oL\xd2\x14e\x94q\x8b\xaatt\xc0\xc1\x0b\xe9\x9fl\x85\x8e r8qG\\#\x91\xaeR\x903\xc3\xbc\x8av8\x0c\xc2s~uL\xfb\xdf1\x18\xb4\xff\x05Y0B6\x1b\x7f|\xdd\x92\x05\x85\x09(\xb3u\xcb\x1e\xc4GZ\x00m+\x8c;\xabd>\xd3\x07e\x1aL\x0d\xe1\x80\xcb\xa2,\xf2c\x89\xa3?\x84\x09\xa5\x02\x84\x92\xa4?\x1b\xa5\x99\x01\xc1|cNz\xcb\x82Ao\xe9x\x88\xd7\xf7!\xfe4\xfd\xec\xb9\xf4R\xf7\x8e\xd5\x80\x92\xe9\x0d\xb3\x8aY\xb5', _namespace)
    dc.install_model(GeneratedSchemaValue, _jsoncompat_init_1, b'x\xda}N\xbb\x0a\x80 \x14\xdd\xfd\x0a1\xc7\xc0\xbd\x9fhk\x09\x07!\x8d $\xd4\x06\x11\xff=5\xbbDH\xdb=\x8f{\xce\x09\x08cB\x17\xa9,\x19pH \xc1I\xec\xa7\x04\x98\x08\xa1\xfd\xa8\x121W\x02\x83TdjdVI\xc7J\x10\xbb\xff\xc1\x11\xfb\xf6\x9b\xf3Gn!\xd6\x99M\xaf/\x7f\xbd8zPI\xf8\xac\x80q?\xed\xb5\x19\xac\xad\xc6\x9c\xcfQ\xbc\x00\x0a\xeb8\xc8', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaValue, 1)], [
        ('model', GeneratedSchema, (("value", "value", 1, True),), None, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["value",1]],"patterns":[],"required":[],"additional":5}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"any":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('root', GeneratedSchemaValue, 2, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"any":[1,5]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"any":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":1,"base_nodes":3,"guards":[],"conversion_validates":[true,true,false],"json_keys":[[0,["\\"value\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaValue,), globals())
