# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassModel):
    value: dc.Omittable[GeneratedSchemaValue] = dc.field("value", default=dc.JSONCOMPAT_MISSING)

    __slots__ = ("value",)


@typing.final
class GeneratedSchemaValue(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaValue", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, value: typing.Any = _jsoncompat_missing) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaValue,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda}PO\x0f\x82 \x14\xbf\xfb)\x1cy\xcc0\x8f~\x89:ui\x1dH@q\x06\x0c^m\xce\xf9\xdd\x03Ds\xadu\xe3\xf7\xef\xf1~oL\xd2\x14e\x94q\x8b\xaatt\xc0\xc1\x0b\xe9\x9fl\x85\x8e r8qG\\#\x91\xaeR\x903\xc3\xbc\x8av8\x0c\xc2s~uL\xfb\xdf1\x18\xb4\xff\x05Y0B6\x1b\x7f|\xdd\x92\x05\x85\x09(\xb3u\xcb\x1e\xc4GZ\x00m+\x8c;\xabd>\xd3\x07e\x1aL\x0d\xe1\x80\xcb\xa2,\xf2c\x89\xa3?\x84\x09\xa5\x02\x84\x92\xa4?\x1b\xa5\x99\x01\xc1|cNz\xcb\x82Ao\xe9x\x88\xd7\xf7!\xfe4\xfd\xec\xb9\xf4R\xf7\x8e\xd5\x80\x92\xe9\x0d\xb3\x8aY\xb5', _namespace)
    dc.install_model(GeneratedSchemaValue, _jsoncompat_init_1, b'x\xda}\x8e\xbd\x0a\x800\x0c\x84\xf7>E\xa9\x8e\x82\xce>\x83\xe0\xe6"\x0e\x82\xf5\x07\xb4\x88\xd6\xa1\x94\xbe\xbbi\xad\xa1Hq\xcb\xe5r\x97O\x13JY:\xf0\xf1d%\xd5 @6\xfdzq\x94\xb0\xe8\x85\xaaGX\xb4~A\xd1rvzp\xeb\xb2$wE\xf9\x93\xc7\x0b\x93\xc5c\xdb"*.&9C\xb6\xc8BG\xaa\xdd\xfeg\xa7<\x161\x05M~\xea\xc8\xab\\\xf7\x87\x0f\xb1\x7f\xb8<\x13\x9eFY\xa2\x1c\xf6kG\xcc\x0d\xe04D\x1c', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaValue, 1)], [
        ('model', GeneratedSchema, (("value", "value", 1, True),), None, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["value",1]],"patterns":[],"required":[],"additional":5}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"any":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('root', GeneratedSchemaValue, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"any":[1,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"any":[3,4]}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":3,"base_nodes":3,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false],"json_keys":[[0,["\\"value\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaValue,), globals())
