# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[typing.Any] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda5\x8cA\x0e\x820\x10E\xf7\x9cb\xd2\xb8\x14\x07\xbb\xe4\x06\x9e\xc1\xb8\x98\xc8\x140P\x9a\xce`4\x84\xbb[*l\xfe\xe2\xfd\xff\xfeR\x00\x98\x93<;\x1e\xc9\xd4`:\xd5 5\xe2K&_\xfe\xf1e\x8a-6\x91\x9c\xa2\xadlU^-\xee\xfb\xf3&\x87\xc8\xae\xff\xdc\x94GI\x07\xf7\x84\x00\x96\x9c\xa9\xd4o\xe0\xedV4\xf6\xbe5\x19\xaf)\x1fY\x9d=\xbfi\x98I\xb99|G\x83p\xb1\xfe\x008\x9c,6', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, b'x\xdaM\xc8;\x0e\x00\x10\x0c\x00\xd0\xdd)\x9a\xce\x06\xb3S8\x03\xe9@\x82\x86."\xee\xee3\x19\xdf\x9b\x0a\x00s,\xaeU\xa6&\x91:Z0\xfa.\xff5\xd7;\x19LGX}\xa2 \xa8\xd6\x06}$\x13v', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 2)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"array":{"prefix":[1],"items":null}},{"unevaluated_items":2}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('union', (2, 4, 5, 6, 7, 8, 9,), None, None),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":3,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}}]}],"patterns":[]}'),
        ("any",),
        ('list', 3),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":4,"base_nodes":10,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,true,false,false,false,false,false,false,false],"json_keys":[[2,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2,), globals())
