# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch1 | GeneratedSchemaBranch2 | collections.abc.Sequence[str] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBranch1(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "GeneratedSchemaBranch1", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaBranch1,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaU\x8d=\x0e\xc20\x0c\x85\xf7\x9e"\x8a\x18[R2\xf6\x06L\x1c\x001\x18\xea\xfe\xa06\xa9\x12\x07\xa9\xaarw\x9cP\x90X\xfc\xec\xcf~\xcf[!\x84<\xf8\xc7\x803\xc8F\xc8\x81h\xf1\x8dROoM\xf5\xc1G\xebz\xd5:\xe8H\xe9Z\xd7\xd5I\xab\xfd\xbeLf0\xeb\xa5c\xeb\x95\x07!\xb6\\\x19\x8f\x84\xb3g\xfc\x05\x8ch]0\xfd\xf0\xe4F\xd3\xcb}\x11\xb3\xc62\x0b\xb9\x80\xdc\xdcrr0\xf8\x82)\x00a{\xfeK\xfb%\xdd\xad\x9d\x10L\x8a\x8aE|\x03k*6\xea', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, b'x\xdaM\xc8;\x0e\x00\x10\x0c\x00\xd0\xdd)\x9a\xce\x06\xb3S8\x03\xe9@\x82\x86."\xee\xee3\x19\xdf\x9b\x0a\x00s,\xaeU\xa6&\x91:Z0\xfa.\xff5\xd7;\x19LGX}\xa2 \xa8\xd6\x06}$\x13v', _namespace)
    dc.install_model(GeneratedSchemaBranch1, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 4), (GeneratedSchemaBranch1, 2)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"any":[1,3]},{"unevaluated_items":4}]},{"types":null,"choices":null,"rules":[{"array":{"prefix":[],"items":2}}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[]},{"types":["boolean"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (2, 4, 5, 7, 6, 8, 9, 10,), None, None),
        ('root', GeneratedSchemaBranch1, 3, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":2,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}}]}],"patterns":[]}'),
        ('list', 6),
        ("str",),
        ("float",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":3,"base_nodes":11,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,true,false,true,false,false,false,false,false,false],"json_keys":[[4,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaBranch1,), globals())
