# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaBar = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBarBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBar(dc.DataclassRootModel):
    root: (GeneratedSchemaBarBranch2 | collections.abc.Sequence[typing.Any] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBarBranch2", "GeneratedSchemaBar", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBar,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"bar\": {\n      \"prefixItems\": [\n        true,\n        {\n          \"type\": \"string\"\n        }\n      ]\n    }\n  },\n  \"$ref\": \"#/$defs/bar\",\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"prefixItems\": [\n    {\n      \"type\": \"string\"\n    }\n  ],\n  \"unevaluatedItems\": false\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1},{"array":{"prefix":[4],"items":null}},{"unevaluated_items":5}]},{"types":null,"choices":null,"rules":[{"array":{"prefix":[2,3],"items":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBarBranch2, _jsoncompat_init_1, "{\n  \"minProperties\": 0,\n  \"properties\": {},\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBar, _jsoncompat_init_2, "{\n  \"prefixItems\": [\n    true,\n    {\n      \"type\": \"string\"\n    }\n  ]\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"array":{"prefix":[1,2],"items":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBarBranch2, 3), (GeneratedSchemaBar, 1)], [
        ('root', GeneratedSchema, 1),
        ('root', GeneratedSchemaBar, 2),
        ('union', (3, 5, 6, 7, 8, 9, 10,), None, None),
        ('model', GeneratedSchemaBarBranch2, (), 4),
        ("any",),
        ('list', 4),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":1,"base_nodes":11,"guards":[],"conversion_validates":[false,false,false,false,false,false,false,false,false,false,false],"json_keys":[[3,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBar,), globals())
