# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2Branch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    foo: dc.Omittable[GeneratedSchemaBranch2Branch2 | collections.abc.Sequence[typing.Any] | float | str | typing.Literal[False] | typing.Literal[True] | None] = dc.field("foo", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2Branch2", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2Branch2, GeneratedSchemaBranch2, GeneratedSchemaItem,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"anyOf\": [\n    {\n      \"properties\": {\n        \"foo\": {\n          \"prefixItems\": [\n            true,\n            {\n              \"type\": \"string\"\n            }\n          ]\n        }\n      }\n    }\n  ],\n  \"properties\": {\n    \"foo\": {\n      \"prefixItems\": [\n        {\n          \"type\": \"string\"\n        }\n      ],\n      \"unevaluatedItems\": false\n    }\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"any":[1]},{"object":{"properties":[["foo",5]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"array":{"prefix":[3,4],"items":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"array":{"prefix":[6],"items":null}},{"unevaluated_items":7}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBranch2Branch2, _jsoncompat_init_1, "{\n  \"minProperties\": 0,\n  \"properties\": {},\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_2, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"minProperties\": 0,\n  \"properties\": {\n    \"foo\": {\n      \"anyOf\": [\n        {\n          \"enum\": [\n            null\n          ]\n        },\n        {\n          \"enum\": [\n            false,\n            true\n          ]\n        },\n        {\n          \"minProperties\": 0,\n          \"properties\": {},\n          \"type\": \"object\"\n        },\n        {\n          \"items\": true,\n          \"minItems\": 0,\n          \"prefixItems\": [\n            true,\n            {\n              \"minLength\": 0,\n              \"type\": \"string\"\n            }\n          ],\n          \"type\": \"array\"\n        },\n        {\n          \"minLength\": 0,\n          \"type\": \"string\"\n        },\n        {\n          \"type\": \"number\"\n        }\n      ]\n    }\n  },\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["foo",1]],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":null,"choices":null,"rules":[{"any":[2,3,4,5,9,10]}]},{"types":null,"choices":[null],"rules":[]},{"types":null,"choices":[false,true],"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[6,7],"items":8}},{"array_length":{"min":0,"max":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]},{"types":["number"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_3, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2Branch2, 4), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 13)], [
        ('root', GeneratedSchema, 1),
        ('union', (2, 12, 7, 8, 9, 10, 11,), None, None),
        ('model', GeneratedSchemaBranch2, (("foo", "foo", 3, True),), 5),
        ('union', (4, 6, 7, 8, 9, 10, 11,), None, None),
        ('model', GeneratedSchemaBranch2Branch2, (), 5),
        ("any",),
        ('list', 5),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",),
        ('list', 13),
        ('root', GeneratedSchemaItem, 5)
    ], b'{"version":1,"base_nodes":14,"guards":[],"conversion_validates":[false,false,false,false,false,false,false,false,false,false,false,false,false,true],"json_keys":[[2,["\\"foo\\":"]],[4,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2Branch2, GeneratedSchemaBranch2, GeneratedSchemaItem,), globals())
