# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: collections.abc.Sequence[typing.Any] = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda5\xcb!\x0e\xc0 \x0c\x85a\xcf)\x9a\xea\x99\xd9\xdd`gX&\x10\xddR\x01!\xa5b\x84p\xf7\x95&\x98\'\xbe?\xaf\x07\x00L\x9cO\xa5T\xf1\x80}\x9bP\x84\x1e\xfe\x96]F\x00\xdd\xd7\xa2\xb6B\xa6XU8\xbf\xe8<lo\xbf\xae\x1aEb\xc30~\xe5\x94\x19R', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[1],"items":null}},{"array_length":{"min":1,"max":null}}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('list', 2),
        ("any",)
    ], b'{"version":2,"base_nodes":3,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
