# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["float"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, float] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaM\x8cM\x0e\x820\x10F\xf7\x9c\xa2i\\\x8a\xc5&n8\x831^a\xb4#\xad\xb1?i\xc7DB\xb8\xbbS`\xc1\xf6}\xef{S#\x84<\x94\xa7E\x0f\xb2\x17\xd2\x12\xa5\xd2+\xf5.1\xb4+>\xc5<(\x93\xe1EJw\xbak\xcfZm\xfe\xb1\x9e\xc1\x18G.\x06\xf8\xdcsL\x98\xc9a\xe1\xd2\xc4\x1b\xaf4&\xac\xdd\xf0\xf5\x0f\xcc\x92\xe1\xbc\xbc\xd2\xea\x8e7\xf0{\xdd\xc3\xef\x8aa \xcb\xe8R\xe5f\xfe\x03\xf5\xe20\xe7', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, b'x\xda\x8d\x92\xc1n\xc3 \x0c\x86\xef}\x8a\x08\xed\x98\x8e,\xd2.}\x83I\xd3\xb6\xfb\xd4\x83\xdb8\x09U\x80\x08\x1c\xa9Q\x95w/PZ%m\x94\x96\x13\xfe\x7f\xfb\x03\x1bN\xab$aov_\xa3\x04\xb6IXM\xd4\xda\x0d\xe7\x07\xab\xd5\xfa"\xbfkS\xf1\xc2@I<\xcf\xf2l\xfd\x91\xf3\x98\x9f\xfab(\x0aAB+h\xfe\x8cn\xd1\x90@\xebH\'\xe79\x97\xfa\x16=Wur\x87\x869q\x08UR\xa8Iz\x16\xd4vB\x18\xc6Z\xff\x03r\x0c\x06\xd5\xff\x96.\xfc\x0fa\x12\xe5`\xa1;l\xe4\xf8\xa5\xba\xa6\xb9\x85\xdb\xb8\x0b\xfc\xe7\xb5%4\x16\xd3\x91@\xa6\xc3\x97`\xb3MFo\xa6\xd5\xe8\\G\xa6w\x07\xdc\x13[\xe0\x0bB\xe9\xcb\xfd\x85\xd2\xc9\xb1_\xd1\xc9f\xb8`\x0c\xf4KX\x09\xc7oT\x15\xd5.\xfbs\xca\xbd\xe9s`KF\xa8j\x89\xfc\xf8\x1bB\xe6\xea:\xc8\xcb\x8b\xdf\x0f`8\x03}k\xa41', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":1}},{"property_names":2}]},{"types":["number"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"string_length":{"min":0,"max":5}}]}],"patterns":[]}'),
        ('union', (2, 4, 3, 7, 8, 9, 10,), None, None),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":1}},{"property_names":2},{"object_length":{"min":0,"max":null}}]},{"types":["number"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"any":[3,4,5,6,8,9]}]},{"types":null,"choices":[null],"rules":[]},{"types":null,"choices":[false,true],"rules":[]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":7}},{"array_length":{"min":0,"max":null}}]},{"types":null,"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":5}}]},{"types":["number"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("float",),
        ('list', 5),
        ('root', GeneratedSchemaItem, 6, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":1,"base_nodes":11,"guards":[],"conversion_validates":[false,false,false,false,false,true,false,false,false,false,false],"json_keys":[[2,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,), globals())
