# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassRootModel):
    root: GeneratedSchemaN1 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: collections.abc.Sequence[GeneratedSchemaN2] = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassRootModel):
    root: GeneratedSchemaN3 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaeQAr\x830\x0c\xbc\xf3\x0a\x8f\xcb1\xc4)\xc7\xdc\xfa\x85N?\xe0b\x01n\xc1J,\xe5\xc0d\xf8{lL<!\xcc\xf8`\xad\xd6\xbb+\xf9^\x08!K\x03-\xc9\xb3\xb8\x87"\x94-b.bW\xbb\xa6G\x1f i\x19F\x92\x87g\x87\xa7\x0bD\x98\xd8[\xd7\xc9\x05\x9eSW\x0e\x96x\xa3\xb2\xf1X\xa0\xa4\xf6\x0aE^\x83\xe3\x08.\xbe\x95?\xbd%\x11\x0e\xbaa\x12\x0e\xc0\x80\x11\x8c\x824[j\'\xc1=\x88_\xc4\x7fp&\xd8\x0b\x0f\xd7\x9b\xf5\xb0<>l$\xcd\xe4\xf4h\x9b\xaf\xb792g^os\x9e\xac\xb4&\xf2\x96!2\xb8\xcf\x9b\xa5\xbf\xa1\x8d\xfc\x8f\x8d\xf0\xbc[\x94\xf6^O\xeb\x9e\x8a\x95\xf0\xf4\xea\x99/tV\x8a\x81\xf8\xf8G\xe8*jz\x18\xf5\x11}\xa7V\x9b\xca\x03\xe1pc\x1b\xba\xb6s\x18\xca*\xfd\x0e)\x8f\x98\xb2\xca\xd2\xa749\xbd,\x93\xd4\xab\xcd\xce\xc1\xeb\x96U}\xaaO\xd5g\xadV~1?\x003\x08\x95\x83', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\x9dPK\x0e\x83 \x10\xdd{\x0aB\xbb\xd4\x0e\xe0\xce\x1b\xf4\x18\xa4B\xb5\x09h`\xba0\x86\xbb\x17,!\xc6\xb4]t7\xef\x9773kE\x08=\xf7J{\xda\x915\x82\x08-+s\x12\x9d\xd2\x11\xd3\x13l6\xb0\x9c\xd6E\xf3\xb7A\x19\x99\xe4\x01q\xf6\x1d\xc0\xc3O\xb6y\xd3\x97\xc9\xdd\xa1wR#\x08&X\xc3\x05d\xff\x96\x0fu\xae\xe3\xfb\xba\x11\x95\xf1;\xe2\xd3\x06\x82f1\x94M\xcch\xaf9\xc9\x0a\x89\xcb\xacRP:\'\x97C\xa9\xf8yc{p\xb7QE\xf7TU\xe6\xbe}\xe5\xff\x8f\x84\x17\xc5z`\xf7', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda}\x8fM\x0e\x83 \x10\x85\xf7\x9e\xc2\xd0.\xb5\x03\xb8\xf3\x06=\x06\xa9Pm\x02\x1a\x98.\x8c\xe1\xee\x05%\xc4\x90\xb6;\xe6\xfd\xe4}lU]\x93\xeb \x95#}\xbd\x85#\x9c\x86\xe6w4\xadT\xe1&\x17\xd8c`\x18i\xb2\xe7\x1e\xa3\xd4"\xda#\xe2\xe2z\x80\x97\x9bM{\xc8\xb7\xd9>a\xb0B!p\xcai\xcb8\xa4\xfc\xde\xf7M\x9ac\xe7\xb9\x09\xa5v\'\xe1\x1b\x01\'\xc9\xf4\x99DO\xe6\x9e\x9a4\x8b\xb8.2\x16\x85\xb5b-F\xf9\xdf?vE\xba\x0b.\xda\xb7\xac\x92V`\xfe@<\xa2%Z\x89\xe5?3\x99\\^', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xda}\x8fA\x0e\x83 \x14D\xf7\x9e\x82\xd0.\xb5\x1fp\xe7\x0dz\x0cR\xa1\xda\x044\xf0\xbb0\x86\xbb\x17,!\xc6\x18w\xcc\xbc\x99\xccg\xad\x08\xa1\xf7^iO;\xb2F\x11\xa5e\xe5\x9d\xa0S:jz\x83-\x06\x96\xd3\xba0\xff\x1a\x94\x91\x09\x0f\x88\xb3\xef\x00>~\xb2\xcd\xdf~L\xee\x0d\xbd\x93\x1aA0\xc1\x1a. \xe7\xb7~\xa8\xf3\x1c\xdf\xcf\x8d\xa8\x8c\xdf\x19g\x17\x08\x9aa(\x97\x98\xd1>s\x93\x15\x13\x97Y\xa5\xa2tN.\x87Qq\xf9\xc7\xf6\x90n#E\xf7UU\xf6N\x1b\xe1\x07\xed\x89N\x10', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 2), (GeneratedSchemaN2, 4), (GeneratedSchemaN3, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":3}}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN0, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":2}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN1, 3, b'{"version":2,"nodes":[{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":1}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('list', 4),
        ('root', GeneratedSchemaN2, 5, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN3, 6, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":3,"base_nodes":7,"guard_nodes":[],"guards":[],"conversion_validates":[true,true,true,false,true,true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3,), globals())
