# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassRootModel):
    root: GeneratedSchemaN3 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: None = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN4(dc.DataclassRootModel):
    root: None = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "GeneratedSchemaN4", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\xadSKn\x830\x10\xdd\xe7\x14\x96\x9be\x08)\xcb\xecz\x85^\xa0r\xc1\x06Wx\x8c\xeci%\x14q\xf7\x0e\xc6\x10\xa3\x90*\x95"y\xe1\xf9\xbfy\xcf\xbe\xec\x18\xe3\xfbJ*\xcf\xcf\xecB\x06\x99\x1e\x85\xc3\xc5\x1c\xe3\xa55F\xc2\xe8\xe3\xd8h\xcf\xe8`#Y+\xa0\xd2P3\xdfYd\xcaY\xc3\xf6N*~X\xea\xaa\x1e\x84\xd1\xe5;9\xa9T\x03H\xf7\xe1K\xdb\xc9\x17j\x03u\x9f\xa4\xeajL\x99F\x07\xe70\xc5x\xcc|\x00\x8e\xd2\xce#\xf3h;\xa6\xac\x0b\xae\x14\xc1\x0d\xac7(\x1b\xebb\x97-4\x09\xe0k\x0c{\xb2\x02TGE\x11\xeb.\xe2\x9d+\x1b\xc4\xce\x9f\xf3\x1c\xa5\xc7\xe3\x97\xb7\x90\xf9\xb2\x91F\x1c\xad\xab\xf38>#\xae\xb2V\x8a\x1fj\x93\xcd\xbe0,7B\x03\x9f\xfaMui\xcf\x9bvN(\xcc\x8bSq\xca^\x8b<\xe6\x87b\xad\xae\xa2\xae5\xde\xe2\xf5\x0e\xb3\x81\xd5m\xd5\x1e\xe12a\x0c\xbe\xcd\xa7t<\x06\x86\x95\xca\x91\xb7d\x18_8%!\xe1\x09\x8bxYZ\xa8V\x9b\x1c\xe2\xbb\x01\xd1\xb2\x8a\xa4\xa2\x0bj\x0b\xcc\xaa\xbb\xaf\xe7\xdf;\xb7\xed\x9f\x1b\xa7\xa8\xf8\x1cr\xd3\x87Y~\xc3\xb0\x1b~\x01`\xf5\x09\xaa', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\xa5P\xcb\x0e\x83 \x10\xbc\xf3\x15d\xdbc\xed*z\xf2W\x9a\x1eL\xc5\xdaF\xb1\x01<\x19\xff\xbd\xf8\x80\x80\x89\xed\xc1\x1b3;3\xbb\xcc@(\x85s\xc9+\x059\x1d\x0c0P\xc4\xee=\x0d\xd5\xa3\xe6ma(\xa8\xb5\xfe\xa8\x1c\xf1\xad:\x11-\xf4\xb5\x93O,eQid1\x8b\xa3\x84\xe1\xaa\xbf\xd8\x80W\xe5\xc5M\x81\x92O\x0c\x9cp\xde\x8b"\x81u8:\x8f\xae\xb9\xf8\xe3b\xceE</\x98\xb4\x9cj\xd9s\x8bY\xf0\x99mJ\x0a\xa1;\xfd\xa9\xce6\xea\xccWs\xd1\xb7\x06\xdf\xdc\xcd\xa2o\x9a\x15\xdc\x89\xbdt\xf6\x1e*\xd5/t\xa7\xcceIP\xe2N\x81#\x19\xbf\x814w\xea', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xda\x85\x8f\xcd\x0e\x820\x10\x84\xef<E\xb3z\x14\x17\x0a\'^\xc5x R\xac\x06\x8a\xe9\xcf\x89\xf0\xee\xb6\xd86\x85\x18\xbduv\xe7\x9b\xce\xce\x19!p\xecX\xaf\xa0!\xb3\x15V\x8a"\xbe\xddR\xdd8\x1b[;\x02\xae\xf5K5\x88O5\x89\xfc3>O\xf2\x8e\x9dl{\x8d\xb4\xa0E^R\xf4\xfeS\x08x\xf4I\x9c\x0b\x94\xccM\xe0\x80\xeb\xbf(J\xf0\xcb%2\x9a3\xf1\x87\xa2\x91\xca\x12\x16lZC\xb44,h\xba9f\x9fR\xc1\x96\xae~\xba\xeb\x9d\xbbN\xddL\x98\xd1\xeaK\xec,\xcc0xq\xcdB\xd3\x95\xfd\xdacy\x03<\xfbX\x11', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda\x85\x8f\xcd\x0e\x820\x10\x84\xef<E\xb3z\x14\x17\x0a\'^\xc5x R\xac\x06\x8a\xe9\xcf\x89\xf0\xee\xb6\xd86\x85\x18\xbdufg\xbe\xee\xce\x19!p\xecX\xaf\xa0!\xb3\x15V\x8a"\xbe\xddP\xdd8\x1b[k\x01\xd7\xfa\xa5\x1a\xc4\xa7\x9aD\xfe\xb1\xcf\x93\xbcc\'\xdb^#-h\x91\x97\x14}\xfe\x14\x00\x8f>\xc19\xa0d\xce\x81\x03\xae\xff\xa2(\xc1\x0f\x97\xd8\xd1\x9c\x89?-\x1a[Y\xd2\x05Kk\x88\x96\x86\x05M7\xc7\xec)\x15l\xdb\xd5\xcft\xbdK\xd7i\x9a\x093Z}\x89;\x0b3\x0c^\\\xb3\xb0\xe9\xda\xfdJ^\xde<\xffX\x12', _namespace)
    dc.install_model(GeneratedSchemaN4, _jsoncompat_init_5, b'x\xda\xab\xe6RPPJ\xcd+\xcdU\xb2R\x88\x06\xb2\x15\x14\xf2Jsr\x80\x8cX\xaeZ\x00c\xd3\x06\xe7', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 3), (GeneratedSchemaN2, 4), (GeneratedSchemaN3, 5), (GeneratedSchemaN4, 7)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"if":{"condition":2,"then_node":4,"else_node":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":null,"rules":[{"ref":7}]},{"types":["null"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN0, 2, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"if":{"condition":1,"then_node":3,"else_node":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":[null],"rules":[]}],"patterns":[]}'),
        ("any",),
        ('root', GeneratedSchemaN1, 2, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN2, 5, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":[null],"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN3, 6, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":[null],"rules":[]}],"patterns":[]}'),
        ("null",),
        ('root', GeneratedSchemaN4, 6, b'{"version":3,"nodes":[{"types":null,"choices":[null],"rules":[]}],"patterns":[]}')
    ], b'{"version":4,"base_nodes":8,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,true,false,false,false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,), globals())
