# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: GeneratedSchemaN2 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: GeneratedSchemaN4 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN4(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "GeneratedSchemaN4", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x85\x8f\xb1\x0e\xc20\x0cD\xf7~E\x14\x18[\\2\xf63\xf8\x83\xa8uh\x11m\xa2$\x0c\xa8\xca\xbf\xe3\xd8,HH\x9d\xac{\xba\xd3\x9d\xf7F)}\x9e\xd0%=\xa8\x9d\x04Ig\x9f\x09I\xf2m\x85\xe5\xf8\xaa\xa8\x1e\x02\xa5\xe5X\x1ag\\-a=\xe7\x1c\xd2\x00\xf0H~\xeb\x04_|\xbc\xc3\x14\xad\xcb`z\xd3wW\x03_?\x87C\xf4\x01c^\xf0O\xb1H\x1e\xf6\xde\xec\xba\x8c7t\xb5\xe5\x04\xbc\x14\xc4\xc7\xa6\xf2\xbb\xef(\xc96\x09\xd67\x9a\xf2\x01\x9f\x05E\xd9', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\xa5P\xc1\x12\x82 \x14\xbc\xf3\x15\x0eu\xd4\x9e\xa2\'\xff\xc6I\xc8\x9aR\x07\xe8\xe4\xf0\xef=\x0c\x0c)\xeb\xd0\x09\xd8}\xbbo\xd9\x89$\x09\xdd\xb7\\(Z\'\x13>\xf0\xd9\xe7\xcb\xdd\x92\xea\xd8\xf1[\x83\x10\xed\xb4\x1eU\x0dpQC\x9f=\xe1\xc3 O\xd0\xcaFh`9\xcb\xb3\x82\x81\x9bO\xbd\xc1(\x87\x91K}\xe6*\xb0E\\4W\xc5W\x90\xdd&\xb9\xb0\xabv0\x87\x82\xbe\xa0\x0bm\xd2\x97X\xcb\xfbom\x19hIx:\'\x8a\xee\xe1Oc=\xa3\xebi\x86\xec\x9c\xda\x03\xe5Wy\x15\xc9+dmn\xe2\xb0\xbf\xaa\xfdT\xeb[\xa5\x9bu\xfaLQ\x8d\x9b\x15\xda\xda\x0c1\x0f\xde\xe0\x84\x98', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda\x85O\xcd\x12\x82 \x10\xbe\xfb\x14\x0cu\xd4\x16\xd1\x93o\xc3$dM\x01\x03tr|\xf7\x16CC\xa7\xa9\x13\xec\xf7\xed\xf7\xb3cA\x08=\xf6Ry\xda\x91\x11\x07\x1c5[\xff\x91\xf4\xe7A>\x04Bt\x08\xc1\xfa\x0e\xe0\xe6\x8d\xae\xde\xf0\xc9\xb8\x0b\xf4N\xa8\x00\x9cqV\xd5\x1c\xd2~\xb9\x18Xg\xact\xe1*}f\x8b\xb8\x12w/7PLsR\xc5\xa8\x03\xcc\xa5@\xd7t\xa5\xa7\xf2#\x0e\xee\xf9_\xdbd\xda"\x7f\x93\x13E\xf7\xfc\xd2\xbd\x9e\xd3\xed6Gvn\xbd\x00\xcdOy\xbb\x93\xb7\xc8\xc6\xdeE\xc2\xbe\x06N/\xf9y[y', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xdaKK\xcc)N\x05\x00\x06\x16\x02\x0c', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda\x85\x8f\xc1\x12\x82 \x10\x86\xef>\x05C\x1d\xb5E\xf4\xe4\xdb0\x09YS\xc0\x00\x9d\x1c\xdf\xbd\xc5\xd0\xd0i\xea\x04\xfb\xff\xfb\xfd\xbb;\x16\x84\xd0c/\x95\xa7\x1d\x19\xb1\xc0R\xb3\xf5\x1fM\x7f\x1e\xe4C\xa0D\x87\x10\xac\xef\x00n\xde\xe8\xea-\x9f\x8c\xbb@\xef\x84\x0a\xc0\x19gU\xcd!\xf5\x97K\x80u\xc6J\x17\xae\xd2g\xb1\xa8+q\xf7r#\xc5iN\xaa8\xea\x00\xf3R\xa0k\xba\xdaS\xf9\x81\x83{\xfeg\x9b\x8c-\xf27%QL\xcf/\xdd\xf3\x9cn\xbb9\xba\xf3\xd6\x8b\xd0\xfc\xc4\xdb\x1d\xde\xa2\x1b\xf7.\x92\xf6\x95\x98^\xf9\x81[{', _namespace)
    dc.install_model(GeneratedSchemaN4, _jsoncompat_init_5, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 3), (GeneratedSchemaN2, 4), (GeneratedSchemaN3, 5), (GeneratedSchemaN4, 6)], [
        ('root', GeneratedSchema, 1, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["false",2],["true",5]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":null,"choices":null,"rules":["false"]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":null,"rules":[{"ref":7}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN0, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["false",1],["true",4]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":["false"]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ('root', GeneratedSchemaN1, 4, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('root', GeneratedSchemaN2, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ('root', GeneratedSchemaN3, 6, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN4, 2, b'{"version":2,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}')
    ], b'{"version":3,"base_nodes":7,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,false,false,true,true],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,), globals())
