# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassAdditionalModel["typing.Any"]):
    bar_item: dc.Omittable[GeneratedSchemaN1] = dc.field("bar-item", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("bar_item", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: GeneratedSchemaN2 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassAdditionalModel["typing.Any"]):
    content: dc.Omittable[GeneratedSchemaN3] = dc.field("content", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("content", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: int = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN4(dc.DataclassRootModel):
    root: int = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "GeneratedSchemaN4", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, bar_item: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, content: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x95R\xcbr\xc3 \x0c\xbc\xf7+<\xd4\xc7\x12R\x1fs\xeb\xf4\x0f\xfa\x07\x04\xcb6i\x0d\x1e\xa1\x1c<\x19\xff{\x01\x07\xc7\xaf\x996GiW\xab]\xc4\xed%\xcbX^B\xe5\xd8)\xbb\xf9\xc2\x97g\x89S\xb1AcKYC`h\xd1\x8c\xcc\xde\xc8V\xab\x0f\xa3\x1a\x1b4&\xe2\xdb\x9cF}\x07\x01t\x84\xda\xd4l\x82\x86\x07\x8bi\x82v+\xbf6\x12\xdb\xbe+\xaf?\xf4\xb9\xeb\xe9\x09_\x0bo\xda\xe35 [\xe0\xc3\xac\x1a\x16\x91r]\xc6\xa9\xe0z\x01th;@\xd2\xb0c\\\xfd\xed\xf8\x0b\xaa\xa0\xfb\x9a\xa8\xff\xb4\x93R\xd8\xf3\x05\xd4l*ML\xecd<\x9c|\xea\x85\x14\xab\x83\xe78\x1a\x89\x017"i\x9dD\x94\xfd\x08\x87M\x91\x9064D\x9d;\x09A\xe0\xe8pq\xd6p\xa7\x1ah\xe5\xc1b-\xeei\xb9\xdf\xc2\xdd\xb7\xee\x1c\x0f\xef\x8f-\x94Z\x12\xf8\xb6\xb3WT Z\xa9\x0d\x1bU\xc7\xe9\xb9\xf2F\x14eE\xa28\x16G\xfe^\x88;?\x0e\xef\x1c%\xbc\x00_}\xba\x9d\xd4\x8fX\xeb\'\x1e~\x01\xf9\x16\xcf\xcb', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\xa5RA\x12\x820\x0c\xbc\xfb\x0a\xa6z\x14\x0b\xd5\x93\x9f\xd0/ \x06(\x03m\xa7\xc4\x83\xc3\xf0w[)\x08\x88:\xea\xad\xddl6\xbb\x99\xd4\x0b\xcf#\xab3$\x15\xd9{\xb5\xf9\x98\xaf\x08\xfa\xb7-Vq\x06ed \x92!\xaajOi^I\xe1\xb7\xf0F\xea\x94\x9eu\x94 e\x01\x0b\xfc\x90Q\xc7_w\x02%\x17G-\x15h\xe4`\xa7\x04}E\x0d\xe1n\xa0\xc1O\x91\xf69B9B\xad\x15\x0d\x89\xf5\xb1\xa4w\xc7T\x84\xa4/7\xee\xd5\xf4\xeaxU`\xd9\xf2\x94C\x8c-\xd3U\x89\xe9\x1cF\x9c\xea\xb2\x09\x9b\x0d\xd9\xdf\xe7\x89\xa5@\x10\xf81\xce\xf6\xe78\xdb\xb7qv\x13\xf6n\x14\xe7R W\x05\x1clO\xf84\x8e\x1b\xeb)h\xa7\xb0p*\x7f]\xc5\xfc\x06\xe7\xb67w\x09/\xaf\xe0an\xba\xaa\xe6\x06\\\xf0\xb6\xec', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda\x9dP\xcb\x0e\x820\x10\xbc\xfb\x15\xa4z\x14\x0b\x95\x13?\xa1\xbf\xc0c\x81\x12h\x9b\xb2\x1e\x0c\xe1\xdfm\xa5\x10@\xa3\xd1[wfvv\xa6\xfd\xce\xf3\xc8!\x87\xa2#\xb1\xd7\x9b\xc1\x8c"\x98\xdf\x96\xec\xb2\x0a\xda\xc4@\xa4BT]Li\xddI\xe1\x8f\xf0I\xea\x92\xe6:)\x90\xb2\x80\x05~\xc8\xa8\xd3\x1f\'\x83\x96\x8b\xab\x96\x0a4r\xb0W\x82\x99QKx:h\xf04\xd1>GhW\xa8\x8d\xa2\xa1\xb09\xf6\xf4\x99\x98\x8a\x90\xcc\xf4\xe0^\xc3\xec\x8ew\x05V-\xd3\x1a2\x1c\x95\x8e%fsYq\xeb\xcb6j\xb6T\xff\xde\'\x93\x02A\xe0\xd7:\xe7\xbf\xeb\x9c?\xd6\x896\xeahU\xe7\xd6 W\x0d\\\xecN\xf8r\x8e\x9b\xe8%h\xe7\xb0s.o\xbflx\x00\xd1\x10\x8b\x0c', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xda\x9d\x90A\x12\x820\x0cE\xf7\x9e\x82\xa9.\xc5Bu\xe5%\xf4\x0a\x08\x01\xca@\xdb)q\xe10\xdc\xddV\x0a\x02\xa2\x8e\xee\xda\x9f\x9f\x9f\xbc4+\xcf#\x9b\x04\xd2\x9a\x1c\xbd\xc6|\xccW\x04\xc3\xdb\x16\xeb8\x87*2\x12\xc9\x11U}\xa4\xb4\xa8\xa5\xf0;y\'uF\x13\x1d\xa5HY\xc0\x02?d\xd4\xf9\xb7}@\xc5\xc5YK\x05\x1a9\xd8)\xc1PQc\xb9\x1fh\xf4K\xa4}\x8ePMT\xbb\x8a\x86\xd4\xee\xb1\xa6\x8f\x8d\xa9\x08\xc9Pn\xdd\xab\x1d\xd2\xf1\xa6\xc0\xba\xe5\xa5\x80\x18;\xa7\xab\x12\xd39F\x9c\xe7\xb2\x99\x9b\x8d\xdd\xbf\xf3\xc4R \x08\xfc\x8a\xb3\xff\x1bg\xff\x11\xe70s\x1f&8\xd7\x12\xb9*\xe1d{\xc2\x97q\xdc\xac\x9e\x81v\x09+\x97\xb2|\x84\xa5\x03,\xc0\xbf\x05\x7f\xc6\xcfa\xdb;\'\xb4\xa3\xef', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda\x9dOK\x0e\x820\x10\xdd{\x0aR]\x8a\x85\xca\x8aK\xe8\x15\xf8\x0cP\x02mS\xc6\x85!\xdc\xddV\x0a\x014\x1a\xdd\xcd\xbcy\xf3>\xfd\xce\xf3\xc8!\x87\xa2#\xb1\xd7\x9b\xc5\xac"\x98g{\xec\xb2\x0a\xda\xc4@\xa4BT]Li\xddI\xe1\x8f\xf0I\xea\x92\xe6:)\x90\xb2\x80\x05~\xc8\xa8\xe3\x1f\'\x81\x96\x8b\xab\x96\x0a4r\xb0.\xc1|QKx24x\x9ah\x9f#\xb4+\xd4F\xd1P\xd8\x1c{\xfaLLEH\xe6\xf3\xe0\xa6aV\xc7\xbb\x02\xcb\x96i\x0d\x19\x8eLw%\xe6sYq\xab\xcb6l\xb6d\xff\xde\'\x93\x02A\xe0\xd7:\xe7\xbf\xeb\x9c?\xd6\x896\xechU\xe7\xd6 W\x0d\\\xecO\xf8b\xc7M\xf4\x12\xb4S\xd89\x95\xb7\x1e\xc3\x03\xd1\x18\x8b\x0e', _namespace)
    dc.install_model(GeneratedSchemaN4, _jsoncompat_init_5, b'x\xda\xab\xe6RPP\xca-\xcd)\xc9,\xc8I\xf5OS\xb2R0\xd4\x01\x09\x95T\x16\xa4\x029J\x99y%\xa9\xe9\xa9EJ\\\xb5\x00\x03\xe1\x0cE', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 2), (GeneratedSchemaN2, 3), (GeneratedSchemaN3, 4), (GeneratedSchemaN4, 7)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["bar-item",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["content",5]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":null,"choices":null,"rules":[{"ref":7}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('model', GeneratedSchemaN0, (("bar-item", "bar_item", 2, True),), 6, b'{"version":3,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["bar-item",1]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["content",4]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":null,"choices":null,"rules":[{"ref":6}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN1, 3, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["content",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('model', GeneratedSchemaN2, (("content", "content", 4, True),), 6, b'{"version":3,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["content",1]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN3, 5, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("int",),
        ("any",),
        ('root', GeneratedSchemaN4, 5, b'{"version":3,"nodes":[{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}')
    ], b'{"version":4,"base_nodes":8,"guard_nodes":[],"guards":[],"conversion_validates":[true,true,true,true,true,false,false,true],"json_keys":[[1,["\\"bar-item\\":"]],[3,["\\"content\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3, GeneratedSchemaN4,), globals())
