# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassModel):
    email: str = dc.field("email")
    kind: typing.Literal["user"] = dc.field("kind")
    name: dc.Omittable[str] = dc.field("name", default=dc.JSONCOMPAT_MISSING)

    __slots__ = ("email", "kind", "name",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, email: typing.Any, kind: typing.Any, name: typing.Any = dc.JSONCOMPAT_MISSING) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"additionalProperties\": false,\n  \"dependentRequired\": {\n    \"name\": [\n      \"email\"\n    ]\n  },\n  \"minProperties\": 2,\n  \"properties\": {\n    \"email\": {\n      \"type\": \"string\"\n    },\n    \"kind\": {\n      \"const\": \"user\"\n    },\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"kind\",\n    \"email\"\n  ],\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["email",1],["kind",2],["name",3]],"patterns":[],"required":["kind","email"],"additional":4}},{"dependencies":[["name",["email"]]]},{"object_length":{"min":2,"max":null}}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":["user"],"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('model', GeneratedSchema, (("email", "email", 1, False), ("kind", "kind", 2, False), ("name", "name", 1, True),), None),
        ("str",),
        ('literal', ("user",))
    ], b'{"version":1,"base_nodes":3,"guards":[],"conversion_validates":[false,false,false],"json_keys":[[0,["\\"email\\":","\\"kind\\":","\\"name\\":"]]]}')


_jsoncompat_bind((GeneratedSchema,), globals())
