# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x95\x8e1\x0e\xc20\x0cE\xf7\x9e"\x8a\x18[R:\xf6\x12\x1c\x001\x04\xea\xb6A%\x09\x8e\x19P\x95\xbb\x93@\x1a\xd1\x01!\x16\xcb~\xf6\xff\xfes\xc1\x18\xdf\xb8\xf3\x08W\xc9[\xc6G"\xebZ!.\xce\xe8\xea\x8d\xb7\x06\x07\xd1\xa1\xecI4uSW\xbbF\xa4\xfb2\x8a\xe54\xed\xfb =\x84\x81\xb1\xf9U\x03\xb6h, )pa\xb7\xd0\xc0O\x12W  zX\x88\xbf\x95&\x18\x00y\xde\xf9\xd4\xf9rqE\xb8\xdd\x15B\x97\xffe\xcf4\x1d\x8b\x0f\xc1\xcf0\xbd1\xdf\xc28B\xa5\x87\xff\xb3D\xcbu\x96"v\xfe\x09\xb8\x88T\'', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,3]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2]],"patterns":[],"required":["bar"],"additional":null}}]},{"types":["integer"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",4]],"patterns":[],"required":["foo"],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":2,"base_nodes":2,"guard_nodes":[],"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
