# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaE\x8bA\x0a\x80 \x10E\xf7\x9eb\x90\x96\xda\x98K/\xd1\x01\xa2\x85\x94&a\x19\x8e\xbb\xe8\xee\x19\x05\xed\xde\xff\xbcw2\x00\xde\xd0\x14\xdcf\xb9\x01\x1eJ9\xc8 \xae\x94v\xf9\xdem\xca\x0b\xce\xd9\xfa\x82Zi%;\x8d\x9f/\x9e\xd8\xc6\xd8\xfb\x9a\x0eu\x00x\x1b\xc9\x89\x1f+\x8d\xec\xba\x01&\\\x1d\x1a', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,1]}]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":4,"base_nodes":2,"guard_nodes":[],"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
