# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassModel):
    children: dc.Omittable[collections.abc.Sequence[GeneratedSchema]] = dc.field("children", default=dc.JSONCOMPAT_MISSING)
    metadata: dc.Omittable[str] = dc.field("metadata", default=dc.JSONCOMPAT_MISSING)
    value: int = dc.field("value")

    __slots__ = ("children", "metadata", "value",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, children: typing.Any = dc.JSONCOMPAT_MISSING, metadata: typing.Any = dc.JSONCOMPAT_MISSING, value: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"additionalProperties\": false,\n  \"properties\": {\n    \"children\": {\n      \"items\": {\n        \"$ref\": \"#\"\n      },\n      \"type\": \"array\"\n    },\n    \"metadata\": {\n      \"type\": \"string\"\n    },\n    \"value\": {\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"value\"\n  ],\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["children",1],["metadata",3],["value",4]],"patterns":[],"required":["value"],"additional":5}}]},{"types":["array"],"choices":null,"rules":[{"array":{"prefix":[],"items":2}}]},{"types":null,"choices":null,"rules":[{"ref":0}]},{"types":["string"],"choices":null,"rules":[]},{"types":["integer"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('model', GeneratedSchema, (("children", "children", 1, True), ("metadata", "metadata", 2, True), ("value", "value", 3, False),), None),
        ('list', 0),
        ("str",),
        ("int",)
    ], b'{"version":1,"base_nodes":4,"guards":[],"conversion_validates":[true,false,false,false],"json_keys":[[0,["\\"children\\":","\\"metadata\\":","\\"value\\":"]]]}')


_jsoncompat_bind((GeneratedSchema,), globals())
