# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: (GeneratedSchemaBranch2 | collections.abc.Sequence[GeneratedSchemaItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBranch2", "GeneratedSchemaItem", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaM\x8bK\x0a\x80 \x14\x00\xf7\x9dB\xa4e\xf5\xcae\xdbN"\xf6\xd1@\x0d\xdf[\x04\xe2\xdd\xb3\x0cj9\xc3L\xac\x18\xe35*\xbdX\xc9G\xc65\xd1\x81#\xc0\x8e\xde\xb5Ew>l0\x07\xb9\x12\x88^\xf4\xed \xe0\xed\x9b{V\xde\x914\x0e\xf3\x1d3\x17\x83\x94q\xc8\x98\x9e\xc6\xcas\xfa2Q\x9cq\x7fW\xa5\x0bTR(\x89', _namespace)
    dc.install_model(GeneratedSchemaBranch2, _jsoncompat_init_1, b'x\xdaM\xcd9\x0e\x80 \x10\x05\xd0\xdeS\x10b\xa9\x0eRz\x0a\xaf\xe02.$,\x81i\x0c\xe1\xee\x0aZ\xd8\xbe\xfc%V\x8c\xf1:,\x07\xea\x89\x0f\x8c\x1fD.\x0c\x00*X\xd3\xbe\xdcY\xbf\xc3\xea\xa7\x8d@\x0a)\xda^\xc2\x97orY\x9ff\xf4\xd6\xa1\xa7\x13\xc33!\x8a\xba?\xc5T\x8c.\x87\xf9\xc3\xce\x0a\x17\xe2U\xba\x01\x82\x9e&_', _namespace)
    dc.install_model(GeneratedSchemaItem, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBranch2, 2), (GeneratedSchemaItem, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"contains":{"node":1,"min":2,"max":2}}]},{"types":null,"choices":[1],"rules":[]}],"patterns":[]}'),
        ('union', (2, 4, 6, 7, 8, 9, 10,), None, None),
        ('model', GeneratedSchemaBranch2, (), 3, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]}],"patterns":[]}'),
        ("any",),
        ('list', 5),
        ('root', GeneratedSchemaItem, 3, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":1,"base_nodes":11,"guards":[],"conversion_validates":[false,false,false,false,false,true,false,false,false,false,false],"json_keys":[[2,[]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBranch2, GeneratedSchemaItem,), globals())
