# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    foo: dc.Omittable[str] = dc.field("foo", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdam\x8f\xcf\x0e\x820\x0c\x87\xef<\xc5\xb2x\x14\x87\x1cy\x09\xbd\x1b\x0f\x05:\xfed\xb2e+&\x86\xf0\xeen f$\\\xba\xec\xfb\xb5_\xd3)a\x8c\x9f\\\xd5\xe2\x0bx\xc1xKd\\!D\xef\xf4\x90\xae\xf8\xa2m#j\x0b\x92D\x9e\xe5Yz\xcd\xc5\xaf\xff\x1c\x86A\xa9\x9b\xf4\xa3\x0f\xffalZ\xaa\xc7\xc6j\x83\x96:t>\xdb\xa8\xe7%\xd8\x1d\xf0\x88>\x06\xc3nG\xb6\x1b\x1a\xfe\x8f\xe6$~C}.\x1b\x0f\xd4\\j\x1di\x0f\x95A0/\x82-\xd5e\x8f\x15\xadg\x8c\x03\xbeA\x8d@X\xdfc\xbf\x04\xe50\x99\xbf/\x1fN\xbc', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('model', GeneratedSchema, (("foo", "foo", 1, True),), 2, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"all":[1]},{"object":{"properties":[["foo",3]],"patterns":[],"required":[],"additional":null}},{"unevaluated_properties":4}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2]],"patterns":[],"required":[],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("str",),
        ("any",)
    ], b'{"version":1,"base_nodes":3,"guards":[],"conversion_validates":[false,false,false],"json_keys":[[0,["\\"foo\\":"]]]}')


_jsoncompat_bind((GeneratedSchema,), globals())
