# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    foo: dc.Omittable[str] = dc.field("foo", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdam\x8fK\x0e\x830\x0cD\xf7\x9c\x02E]BCYr\x8a\xee\xab.\x02\x98\x9fh\x9c:\xa6R\x85\xb8{\xc3\xaf\x02\xc4\xce3\xe37qz\xcf\xf7\xc5\xc5f\x15\xbc\x94H|Q1\x1b\x9bH\xd9X\xd4\xe1l_\x91J\x99\x93*X\xc6Q\x1c\x85\xb7X.\xfb\xc1\x08kd\x07\xf6n<\x08\'\x0d\xa1\x01\xe2\x1a\xec\xc6u~\xaahg8+CmGv\xca\xfe\xc1\xb0LC\xb0V\x12\xbc\xbb\x9a w\xab\x8f}\xe1\xa2\x9e\xde\x0aN\xd0\xd9\x0d\xa2@\xdc\x9e\xc9_\x03\xe3\xd3\x96\xa9\xd6\xa58\x14\xac)\xa6\x0dd<\x7f\xba\xd3\xf0Qm\xa7\x18\xf2\xfb\xb6\xbfP\xad\x05o\xf8\x01\xa2\xf6XK', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('model', GeneratedSchema, (("foo", "foo", 1, True),), 2, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"not":1},{"object":{"properties":[["foo",4]],"patterns":[],"required":[],"additional":null}},{"unevaluated_properties":5}]},{"types":null,"choices":null,"rules":[{"not":2}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",3]],"patterns":[],"required":["bar"],"additional":null}}]},{"types":null,"choices":["bar"],"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("str",),
        ("any",)
    ], b'{"version":2,"base_nodes":3,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false],"json_keys":[[0,["\\"foo\\":"]]]}')


_jsoncompat_bind((GeneratedSchema,), globals())
