# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    foo: dc.Omittable[str] = dc.field("foo", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBarBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    bar: dc.Omittable[str] = dc.field("bar", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("bar", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBarItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBar(dc.DataclassRootModel):
    root: (GeneratedSchemaBarBranch2 | collections.abc.Sequence[GeneratedSchemaBarItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBarBranch2", "GeneratedSchemaBarItem", "GeneratedSchemaBar", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, bar: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBarItem, GeneratedSchemaBar,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"bar\": {\n      \"properties\": {\n        \"bar\": {\n          \"type\": \"string\"\n        }\n      }\n    }\n  },\n  \"$ref\": \"#/$defs/bar\",\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"properties\": {\n    \"foo\": {\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\",\n  \"unevaluatedProperties\": false\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"ref":1},{"object":{"properties":[["foo",3]],"patterns":[],"required":[],"additional":null}},{"unevaluated_properties":4}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2]],"patterns":[],"required":[],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBarBranch2, _jsoncompat_init_1, "{\n  \"minProperties\": 0,\n  \"properties\": {\n    \"bar\": {\n      \"minLength\": 0,\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["bar",1]],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBarItem, _jsoncompat_init_2, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaBar, _jsoncompat_init_3, "{\n  \"properties\": {\n    \"bar\": {\n      \"type\": \"string\"\n    }\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",1]],"patterns":[],"required":[],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBarBranch2, 3), (GeneratedSchemaBarItem, 4), (GeneratedSchemaBar, 5)], [
        ('model', GeneratedSchema, (("foo", "foo", 1, True),), 2),
        ("str",),
        ("any",),
        ('model', GeneratedSchemaBarBranch2, (("bar", "bar", 1, True),), 2),
        ('root', GeneratedSchemaBarItem, 2),
        ('root', GeneratedSchemaBar, 6),
        ('union', (3, 7, 8, 1, 9, 10, 11,), None, None),
        ('list', 4),
        ("float",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":1,"base_nodes":12,"guards":[{"owner":3,"field":0,"original":1,"guard":{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]}}],"conversion_validates":[false,false,false,false,true,false,false,false,false,false,false,false,false],"json_keys":[[0,["\\"foo\\":"]],[3,["\\"bar\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBarItem, GeneratedSchemaBar,), globals())
