# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassAdditionalModel["typing.Any"]):
    foo: dc.Omittable[str] = dc.field("foo", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("foo", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBarBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    bar: dc.Omittable[str] = dc.field("bar", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("bar", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaBarItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaBar(dc.DataclassRootModel):
    root: (GeneratedSchemaBarBranch2 | collections.abc.Sequence[GeneratedSchemaBarItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaBarBranch2", "GeneratedSchemaBarItem", "GeneratedSchemaBar", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

_jsoncompat_missing = dc.JsoncompatMissingType()

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, foo: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, bar: typing.Any = _jsoncompat_missing, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBarItem, GeneratedSchemaBar,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdamOK\x0e\x820\x10\xdds\x0aR]\x8aE\x96\x9c\xc2+\x14\x98\xf2\x09\xd2ff01\x84\xbb\xdb\x16\xc5&\xb2i\xf3>\xf3\xe6\xcd\x92\xa4\xa987\xa0I\x94\xe9\xe2\x80\x83\x95\xc2\x1d8h\xd1X@\xee\x81"\xf6\xcf\x16(~Yp\x9c \xc6~j\xc5.\xadI\xfc\xfbw\xbd\x84\xc5\x08\xda\xfbO2T\x90>r\x13\xa8\xee\xe0\xa1\xbc\xd61[*\xa5\x1c\xc8L\xd9F_\x0d\xb6\xb2A\xa5Y\x16y\x91g\xb7B~\xfca\xf8\xa0\xb0\xd0\xc6\xc47\x1d\x15\xfd\xd5\xfa\xaa\xa6\x1a\xa0\xe6-t\x9e\xe0\xa9\xc6Y14\xf78_\xab\x91 Y\xdf4\xa8V\xdc', _namespace)
    dc.install_model(GeneratedSchemaBarBranch2, _jsoncompat_init_1, b'x\xdaM\xcc1\x0a\x800\x0c\x05\xd0\xbd\xa7(\x99\x1d\x9c=\x83\x83W\xb0\x12j\x05\xdb\x92f\x91\xd2\xbb\x1b#\x15\x97@\xde\xe7\xffj\xac\x853\xc4\x85RF\xe2\x80\x05&;\x0e\x8f\xe6?U\x111\xb7\xd2\xf7\xbc\xc5\x19\xa3\xe7\xbd\x97T\xf9\xca(\x00\x85)D\x0f\xcaMn\xd3\xd9\x9e&w\xe0\xc6`\xda\x0dI\x00#\x0e', _namespace)
    dc.install_model(GeneratedSchemaBarItem, _jsoncompat_init_2, b'x\xda+)*M\x05\x00\x04y\x01\xc1', _namespace)
    dc.install_model(GeneratedSchemaBar, _jsoncompat_init_3, b'x\xda=\xc81\x0a\x00 \x08@\xd1\xbdS\x88\xc7\xe86\x05\x12-%\xe6\x12\xe2\xdd\xb3\x86\x86?\xfcg\x09\x00Y&\x93h\xa7\x85\x19,$\xac\x16\xf9\x13\xab\x9b)\x1e\x97J\x1f\x0d\x1f{\xba\xf9\x01fj\x11^', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaBarBranch2, 3), (GeneratedSchemaBarItem, 4), (GeneratedSchemaBar, 5)], [
        ('model', GeneratedSchema, (("foo", "foo", 1, True),), 2, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"ref":1},{"object":{"properties":[["foo",2]],"patterns":[],"required":[],"additional":null}},{"unevaluated_properties":3}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2]],"patterns":[],"required":[],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("str",),
        ("any",),
        ('model', GeneratedSchemaBarBranch2, (("bar", "bar", 1, True),), 2, b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["bar",1]],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]}],"patterns":[]}'),
        ('root', GeneratedSchemaBarItem, 2, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaBar, 6, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",1]],"patterns":[],"required":[],"additional":null}}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('union', (3, 7, 8, 1, 9, 10, 11,), None, None),
        ('list', 4),
        ("float",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",)
    ], b'{"version":2,"base_nodes":12,"guard_nodes":[{"original":1,"guard":{"types":["string"],"choices":null,"rules":[{"string_length":{"min":0,"max":null}}]}}],"guards":[{"owner":3,"field":0,"guard":0}],"conversion_validates":[false,false,false,false,true,false,false,false,false,false,false,false,false],"json_keys":[[0,["\\"foo\\":"]],[3,["\\"bar\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaBarBranch2, GeneratedSchemaBarItem, GeneratedSchemaBar,), globals())
