# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xdaU\x8c\xbb\x0e\xc20\x0cE\xf7~E\x141\xb6\xa4d\xecO\xc0\x8e\x18,\xeaPPh\xa2\xd8a\xa9\xf2\xef\xb8\x0f$\xba\xd8\xf2\xf1=w\xaa\x94\xd2\x07\xba\x0f\xf8\x06\xdd)=0G\xea\x8cyQ\x18\x9b\x15\x1fCz\x98>\x81cc[\xdb6\'k\xb6|=\xcb\xe0\xfd\xd9\x89z\x95C\xa9i\x99\x82c\x0a\x11\x13?\x91\xe4\xf7\xa3\xc2]\x08\x028e\xdcXYv\xa9\xf7z\x1e\xf1\x03>\x03c\x7f\xf9or\xe0i5g\xefV\x95/\\\x974i', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0)], [
        ('root', GeneratedSchema, 1, b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,3]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"unevaluated_properties":4}]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}'),
        ("any",)
    ], b'{"version":2,"base_nodes":2,"guard_nodes":[],"guards":[],"conversion_validates":[false,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema,), globals())
