# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaOneBranch2A(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaOneBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    a: dc.Omittable[GeneratedSchemaOneBranch2A] = dc.field("a", default=dc.JSONCOMPAT_MISSING)
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("a", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaOneItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaOne(dc.DataclassRootModel):
    root: (GeneratedSchemaOneBranch2 | collections.abc.Sequence[GeneratedSchemaOneItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaTwoBranch2X(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaTwoBranch2(dc.DataclassAdditionalModel["typing.Any"]):
    x: GeneratedSchemaTwoBranch2X = dc.field("x")
    __jsoncompat_extra__: collections.abc.Mapping[str, typing.Any] = dc.extra_field(default_factory=dict)

    __slots__ = ("x", "__jsoncompat_extra__",)


@typing.final
class GeneratedSchemaTwoItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaTwo(dc.DataclassRootModel):
    root: (GeneratedSchemaTwoBranch2 | collections.abc.Sequence[GeneratedSchemaTwoItem] | float | str | typing.Literal[False] | typing.Literal[True] | None) = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaOneBranch2A", "GeneratedSchemaOneBranch2", "GeneratedSchemaOneItem", "GeneratedSchemaOne", "GeneratedSchemaTwoBranch2X", "GeneratedSchemaTwoBranch2", "GeneratedSchemaTwoItem", "GeneratedSchemaTwo", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, a: typing.Any = dc.JSONCOMPAT_MISSING, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_5(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_6(self: dc.DataclassModel, *, skip_validation: bool = False, x: typing.Any, __jsoncompat_extra__: typing.Any = dc.EXTRA_DEFAULT) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_7(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_8(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaOneBranch2A, GeneratedSchemaOneBranch2, GeneratedSchemaOneItem, GeneratedSchemaOne, GeneratedSchemaTwoBranch2X, GeneratedSchemaTwoBranch2, GeneratedSchemaTwoItem, GeneratedSchemaTwo,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"one\": {\n      \"properties\": {\n        \"a\": true\n      }\n    },\n    \"two\": {\n      \"properties\": {\n        \"x\": true\n      },\n      \"required\": [\n        \"x\"\n      ]\n    }\n  },\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"allOf\": [\n    {\n      \"$ref\": \"#/$defs/one\"\n    },\n    {\n      \"properties\": {\n        \"b\": true\n      }\n    },\n    {\n      \"oneOf\": [\n        {\n          \"$ref\": \"#/$defs/two\"\n        },\n        {\n          \"properties\": {\n            \"y\": true\n          },\n          \"required\": [\n            \"y\"\n          ]\n        }\n      ]\n    }\n  ],\n  \"unevaluatedProperties\": false\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,4,6]},{"unevaluated_properties":12}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["a",3]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["b",5]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"one":[7,10]}]},{"types":null,"choices":null,"rules":[{"ref":8}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["x",9]],"patterns":[],"required":["x"],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["y",11]],"patterns":[],"required":["y"],"additional":null}}]},{"types":null,"choices":null,"rules":[]},{"types":null,"choices":null,"rules":["false"]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaOneBranch2A, _jsoncompat_init_1, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaOneBranch2, _jsoncompat_init_2, "{\n  \"minProperties\": 0,\n  \"properties\": {\n    \"a\": true\n  },\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["a",1]],"patterns":[],"required":[],"additional":null}},{"object_length":{"min":0,"max":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaOneItem, _jsoncompat_init_3, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaOne, _jsoncompat_init_4, "{\n  \"properties\": {\n    \"a\": true\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["a",1]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaTwoBranch2X, _jsoncompat_init_5, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaTwoBranch2, _jsoncompat_init_6, "{\n  \"minProperties\": 1,\n  \"properties\": {\n    \"x\": true\n  },\n  \"required\": [\n    \"x\"\n  ],\n  \"type\": \"object\"\n}", b'{"version":1,"nodes":[{"types":["object"],"choices":null,"rules":[{"object":{"properties":[["x",1]],"patterns":[],"required":["x"],"additional":null}},{"object_length":{"min":1,"max":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaTwoItem, _jsoncompat_init_7, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaTwo, _jsoncompat_init_8, "{\n  \"properties\": {\n    \"x\": true\n  },\n  \"required\": [\n    \"x\"\n  ]\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["x",1]],"patterns":[],"required":["x"],"additional":null}}]},{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaOneBranch2A, 2), (GeneratedSchemaOneBranch2, 3), (GeneratedSchemaOneItem, 4), (GeneratedSchemaOne, 5), (GeneratedSchemaTwoBranch2X, 13), (GeneratedSchemaTwoBranch2, 14), (GeneratedSchemaTwoItem, 15), (GeneratedSchemaTwo, 16)], [
        ('root', GeneratedSchema, 1),
        ("any",),
        ('root', GeneratedSchemaOneBranch2A, 1),
        ('model', GeneratedSchemaOneBranch2, (("a", "a", 2, True),), 1),
        ('root', GeneratedSchemaOneItem, 1),
        ('root', GeneratedSchemaOne, 6),
        ('union', (3, 7, 8, 9, 10, 11, 12,), None, None),
        ('list', 4),
        ("float",),
        ("str",),
        ('literal', (False,)),
        ('literal', (True,)),
        ("null",),
        ('root', GeneratedSchemaTwoBranch2X, 1),
        ('model', GeneratedSchemaTwoBranch2, (("x", "x", 13, False),), 1),
        ('root', GeneratedSchemaTwoItem, 1),
        ('root', GeneratedSchemaTwo, 17),
        ('union', (14, 18, 8, 9, 10, 11, 12,), None, None),
        ('list', 15)
    ], b'{"version":1,"base_nodes":19,"guards":[],"conversion_validates":[false,false,true,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false],"json_keys":[[3,["\\"a\\":"]],[14,["\\"x\\":"]]]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaOneBranch2A, GeneratedSchemaOneBranch2, GeneratedSchemaOneItem, GeneratedSchemaOne, GeneratedSchemaTwoBranch2X, GeneratedSchemaTwoBranch2, GeneratedSchemaTwoItem, GeneratedSchemaTwo,), globals())
