//! Public declarations first; precomputed implementation in a separable footer.

use super::plan::{ConversionNode, PreparedModule, ScalarKind};
use super::{
    ClassKind, ClassSpec, DataclassError, EXTRA_FIELD_NAME, omittable_annotation,
    python_json_literal, python_string_literal, render_class_base,
};
use std::fmt::Write;

/// Two parts of one generated format. The implementation has no model imports:
/// the public module passes its classes to the binder after declaring them.
pub struct DataclassModule {
    pub imports: String,
    pub declarations: String,
    pub implementation: String,
    pub models: Vec<String>,
}
impl DataclassModule {
    pub fn single_file(&self) -> String {
        format!(
            "{}{}\n# --- Generated implementation: regenerate this file to change it. ---\n\n{}\n_jsoncompat_bind({}, globals())\n",
            self.imports,
            self.declarations,
            self.implementation,
            self.model_tuple()
        )
    }
    pub fn public_file(&self, companion: &str) -> String {
        format!(
            "{}if __package__:\n    from .{companion} import bind_models as _jsoncompat_bind\nelse:\n    from {companion} import bind_models as _jsoncompat_bind\n\n{}\n_jsoncompat_bind({}, globals())\ndel _jsoncompat_bind\n",
            self.imports,
            self.declarations,
            self.model_tuple()
        )
    }
    pub fn private_file(&self) -> String {
        format!(
            "# Generated implementation. Import the public model module instead.\nfrom __future__ import annotations\n\nimport typing\nfrom jsoncompat.codegen import dataclasses as dc\n\n__all__ = (\"bind_models\",)\n\n{}\nbind_models = _jsoncompat_bind\n",
            self.implementation
        )
    }
    fn model_tuple(&self) -> String {
        format!("({},)", self.models.join(", "))
    }
}

struct Field {
    name: String,
    annotation: String,
    expression: String,
    default: Option<&'static str>,
}
fn fields(class: &ClassSpec) -> Vec<Field> {
    match &class.kind {
        ClassKind::Root { annotation } => vec![Field {
            name: "root".into(),
            annotation: annotation.to_string(),
            expression: "dc.root_field()".into(),
            default: None,
        }],
        ClassKind::Object {
            fields,
            extra_annotation,
        } => {
            let mut result = fields
                .iter()
                .map(|field| Field {
                    name: field.py_name.clone(),
                    annotation: if field.required {
                        field.annotation.to_string()
                    } else {
                        omittable_annotation(&field.annotation)
                    },
                    expression: format!(
                        "dc.field({}{})",
                        python_string_literal(&field.json_name),
                        if field.required {
                            ""
                        } else {
                            ", default=dc.JSONCOMPAT_MISSING"
                        }
                    ),
                    default: if field.required {
                        None
                    } else {
                        Some("dc.JSONCOMPAT_MISSING")
                    },
                })
                .collect::<Vec<_>>();
            if let Some(annotation) = extra_annotation {
                result.push(Field {
                    name: EXTRA_FIELD_NAME.into(),
                    annotation: format!("collections.abc.Mapping[str, {annotation}]"),
                    expression: "dc.extra_field(default_factory=dict)".into(),
                    default: Some("dc.EXTRA_DEFAULT"),
                });
            }
            result
        }
    }
}
fn tuple(items: impl IntoIterator<Item = String>) -> String {
    let items = items.into_iter().collect::<Vec<_>>();
    if items.is_empty() {
        "()".into()
    } else {
        format!("({},)", items.join(", "))
    }
}
fn bytes(bytes: &[u8]) -> String {
    let mut out = String::from("b'");
    for byte in bytes {
        match byte {
            b'\'' => out.push_str("\\'"),
            b'\\' => out.push_str("\\\\"),
            32..=126 => out.push(*byte as char),
            _ => write!(out, "\\x{byte:02x}").expect("string write"),
        }
    }
    out.push('\'');
    out
}

pub(super) fn module(classes: &[ClassSpec], root: &str) -> Result<DataclassModule, DataclassError> {
    let prepared = PreparedModule::compile(classes)?;
    let mut imports = String::from(
        "# Generated by jsoncompat. Edit the schema and regenerate this module.\nfrom __future__ import annotations\n\nimport collections.abc\nimport typing\n\nfrom jsoncompat.codegen import dataclasses as dc\n\n",
    );
    let mut declarations = String::new();
    let mut implementation = String::new();
    for (index, class) in classes.iter().enumerate() {
        let fields = fields(class);
        writeln!(
            declarations,
            "\n@typing.final\nclass {}({}):",
            class.name,
            render_class_base(class)
        )
        .expect("string write");
        for field in &fields {
            writeln!(
                declarations,
                "    {}: {} = {}",
                field.name, field.annotation, field.expression
            )
            .expect("string write");
        }
        writeln!(
            declarations,
            "\n    __slots__ = {}\n",
            tuple(fields.iter().map(|f| python_string_literal(&f.name)))
        )
        .expect("string write");
        let mut parameters = vec![
            "self: dc.DataclassModel".into(),
            "*".into(),
            "skip_validation: bool = False".into(),
        ];
        parameters.extend(fields.iter().map(|field| {
            format!(
                "{}: {}{}",
                field.name,
                "typing.Any",
                field.default.map(|d| format!(" = {d}")).unwrap_or_default()
            )
        }));
        writeln!(
            implementation,
            "def _jsoncompat_init_{index}({}) -> None:\n    self.__post_init__(skip_validation)\n",
            parameters.join(", ")
        )
        .expect("string write");
    }
    writeln!(declarations, "JSONCOMPAT_MODEL = {root}\n").expect("string write");
    writeln!(
        declarations,
        "__all__ = {}",
        tuple(
            classes
                .iter()
                .map(|c| python_string_literal(&c.name))
                .chain(std::iter::once(python_string_literal("JSONCOMPAT_MODEL")))
        )
    )
    .expect("string write");
    implementation
        .push_str("def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:\n");
    writeln!(
        implementation,
        "    {} = _models",
        tuple(classes.iter().map(|c| c.name.clone()))
    )
    .expect("string write");
    for (index, class) in classes.iter().enumerate() {
        let program = prepared.graph.schemas[index]
            .to_bytes()
            .map_err(|error| super::invalid_schema(class.name.clone(), error))?;
        writeln!(
            implementation,
            "    dc.install_model({}, _jsoncompat_init_{index}, {}, {}, _namespace)",
            class.name,
            python_string_literal(&class.schema_json),
            bytes(&program)
        )
        .expect("string write");
    }
    let roots = classes
        .iter()
        .zip(&prepared.roots)
        .map(|(class, id)| format!("({}, {})", class.name, id.0))
        .collect::<Vec<_>>()
        .join(", ");
    let descriptors = prepared
        .graph
        .nodes
        .iter()
        .map(|node| match node {
            ConversionNode::Scalar { kind } => format!(
                "({:?},)",
                match kind {
                    ScalarKind::Any => "any",
                    ScalarKind::String => "str",
                    ScalarKind::Integer => "int",
                    ScalarKind::Number => "float",
                    ScalarKind::Boolean => "bool",
                    ScalarKind::Null => "null",
                }
            ),
            ConversionNode::Literal { values } => format!(
                "('literal', {})",
                tuple(values.iter().map(python_json_literal))
            ),
            ConversionNode::List { item } => format!("('list', {})", item.0),
            ConversionNode::Dict { value } => format!("('dict', {})", value.0),
            ConversionNode::Root { model, value } => {
                format!("('root', {}, {})", classes[*model].name, value.0)
            }
            ConversionNode::Model {
                model,
                fields,
                extra,
            } => format!(
                "('model', {}, {}, {})",
                classes[*model].name,
                tuple(fields.iter().map(|f| format!(
                    "({}, {}, {}, {})",
                    python_string_literal(&f.json_name),
                    python_string_literal(&f.py_name),
                    f.value_node.0,
                    if f.presence.is_omittable() {
                        "True"
                    } else {
                        "False"
                    }
                ))),
                extra
                    .as_ref()
                    .map(|e| e.value_node.0.to_string())
                    .unwrap_or_else(|| "None".into())
            ),
            ConversionNode::Union(union) => {
                let (name, entries) = union
                    .discriminator
                    .as_ref()
                    .map(|(name, entries)| {
                        (
                            python_string_literal(name),
                            tuple(entries.iter().map(|(value, index)| {
                                format!("({}, {index})", python_json_literal(value))
                            })),
                        )
                    })
                    .unwrap_or_else(|| ("None".into(), "None".into()));
                format!(
                    "('union', {}, {name}, {entries})",
                    tuple(union.branches.iter().map(|id| id.0.to_string()))
                )
            }
        })
        .collect::<Vec<_>>()
        .join(",\n        ");
    let plan = serde_json::to_vec(&prepared.decisions).expect("serializable model plan");
    writeln!(
        implementation,
        "    dc.bind_module(1, [{roots}], [\n        {descriptors}\n    ], {})\n",
        bytes(&plan)
    )
    .expect("string write");
    if !classes
        .iter()
        .flat_map(fields)
        .any(|field| field.annotation.contains("collections.abc."))
    {
        imports = imports.replace("import collections.abc\n", "");
    }
    Ok(DataclassModule {
        imports,
        declarations,
        implementation,
        models: classes.iter().map(|c| c.name.clone()).collect(),
    })
}
