name: Python examples

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pydantic_golden:
    name: Test pydantic_golden
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/python/pydantic_golden

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run pytest
        run: |
          uv sync --dev
          uv run --dev pytest

  basic:
    name: Test basic
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/python/basic

    steps:

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run the demo smoketest
        run: |
          uv run --prerelease=allow demo.py
