name: Python examples

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pydantic_golden:
    name: Test pydantic_golden
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/python/pydantic_golden

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Run pytest
        run: |
          uv run pytest


