name: Website checks

on:
  push:
    branches: [main]
    paths:
      - 'web/jsoncompatdotcom/**'
  pull_request:
    paths:
      - 'web/jsoncompatdotcom/**'
  workflow_dispatch:

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: web/jsoncompatdotcom/pnpm-lock.yaml

      - name: Install website dependencies (frozen lockfile)
        working-directory: web/jsoncompatdotcom
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Biome checks
        working-directory: web/jsoncompatdotcom
        run: pnpm run ci
