# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaInt(dc.DataclassRootModel):
    root: int = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaInt", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaInt,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"int\": {\n      \"type\": \"integer\"\n    }\n  },\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"allOf\": [\n    {\n      \"properties\": {\n        \"foo\": {\n          \"$ref\": \"#/$defs/int\"\n        }\n      }\n    },\n    {\n      \"additionalProperties\": {\n        \"$ref\": \"#/$defs/int\"\n      }\n    }\n  ]\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"all":[1,4]}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":["integer"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"object":{"properties":[],"patterns":[],"required":[],"additional":5}}]},{"types":null,"choices":null,"rules":[{"ref":3}]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaInt, _jsoncompat_init_1, "{\n  \"type\": \"integer\"\n}", b'{"version":1,"nodes":[{"types":["integer"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaInt, 2)], [
        ('root', GeneratedSchema, 1),
        ("any",),
        ('root', GeneratedSchemaInt, 3),
        ("int",)
    ], b'{"version":1,"base_nodes":4,"guards":[],"conversion_validates":[false,false,true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaInt,), globals())
