# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import collections.abc
import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaReffedItem(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaReffed(dc.DataclassRootModel):
    root: collections.abc.Sequence[GeneratedSchemaReffedItem] = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaReffedItem", "GeneratedSchemaReffed", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaReffedItem, GeneratedSchemaReffed,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, "{\n  \"$defs\": {\n    \"reffed\": {\n      \"type\": \"array\"\n    }\n  },\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"properties\": {\n    \"foo\": {\n      \"$ref\": \"#/$defs/reffed\",\n      \"maxItems\": 2\n    }\n  }\n}", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["foo",1]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2},{"array_length":{"min":0,"max":2}}]},{"types":["array"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaReffedItem, _jsoncompat_init_1, "true", b'{"version":1,"nodes":[{"types":null,"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.install_model(GeneratedSchemaReffed, _jsoncompat_init_2, "{\n  \"type\": \"array\"\n}", b'{"version":1,"nodes":[{"types":["array"],"choices":null,"rules":[]}],"patterns":[]}', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaReffedItem, 2), (GeneratedSchemaReffed, 3)], [
        ('root', GeneratedSchema, 1),
        ("any",),
        ('root', GeneratedSchemaReffedItem, 1),
        ('root', GeneratedSchemaReffed, 4),
        ('list', 2)
    ], b'{"version":1,"base_nodes":5,"guards":[],"conversion_validates":[false,false,true,true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaReffedItem, GeneratedSchemaReffed,), globals())
