# Generated by jsoncompat. Edit the schema and regenerate this module.
from __future__ import annotations

import typing

from jsoncompat.codegen import dataclasses as dc


@typing.final
class GeneratedSchema(dc.DataclassRootModel):
    root: GeneratedSchemaN0 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN0(dc.DataclassRootModel):
    root: GeneratedSchemaN1 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN1(dc.DataclassRootModel):
    root: GeneratedSchemaN2 = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN2(dc.DataclassRootModel):
    root: typing.Any = dc.root_field()

    __slots__ = ("root",)


@typing.final
class GeneratedSchemaN3(dc.DataclassRootModel):
    root: str = dc.root_field()

    __slots__ = ("root",)

JSONCOMPAT_MODEL = GeneratedSchema

__all__ = ("GeneratedSchema", "GeneratedSchemaN0", "GeneratedSchemaN1", "GeneratedSchemaN2", "GeneratedSchemaN3", "JSONCOMPAT_MODEL",)

# --- Generated implementation: regenerate this file to change it. ---

def _jsoncompat_init_0(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_1(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_2(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_3(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_init_4(self: dc.DataclassModel, *, skip_validation: bool = False, root: typing.Any) -> None:
    self.__post_init__(skip_validation)

def _jsoncompat_bind(_models: tuple[type[dc.DataclassModel], ...], _namespace: dict[str, typing.Any]) -> None:
    (GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3,) = _models
    dc.install_model(GeneratedSchema, _jsoncompat_init_0, b'x\xda\x9d\x90A\x0e\x83 \x10E\xf7\x9e\xc2\xd0.\x8b\xa8Ko\x83:*\x8d\x0a\x190ic\xb8{A\xd4hj\xba\xe8\x0e\xde\xcc\xff\x7ff\xe6(\x8e\xc9]\xd4\xa4\x88Ig\x8c*\x18\x83\x17\x1fT\x0fI%\x07\xa6\xab\x0e\x06N\x11\x1aMy\xa9e?\x19\xa0\x13\x0aMk\x87\xb2\xe4\xa9\xe5H\x1e\x8b\x87\xeb\xf1&\xbf\x15\xf9Q\x11Z\xb7d\xed\xa2}\x91\x06\x9cHlY\x8d\xbc1,O\xf3\x94f\xf9:L\x10+\x94\x0a\xd0\x08\xd0N?;\xe2X#\xe5\xfe\xf1\xfe>\xf0\x00\x1c\x12\xe3\x08xB\xd7V{\xad\xe4\xf8\x05\x1d6o\x05\xcb\xb2\x06\xc5\xd8\x92S\xd9FW\xef\xede\x1f\xfbx\x7f\x1e\xfdp\xc2\xe0\xb3\x1e\xfe\xc6\x96\x85Y\xd81\xdaBmd?\xb7\xa4\x84\xa1', _namespace)
    dc.install_model(GeneratedSchemaN0, _jsoncompat_init_1, b'x\xda\xa5QA\x0e\x83 \x10\xbc\xf3\x0aC{\xac\x05\xf1\xe6\x1b\xfa\x09[Am"\x90e/\x8d\xf1\xefEK\x086Z\x0f=\xc1\xceLvgwF\x92e\xf4\xdcH\xe5h\x95\x8d\xbe\xf0\xa5\xe6\xf1?\x93 \x95\xaf\xe9\x89-2\xa6\x0bz\x89\x9c{tr\xa8g\xbaC\xb4\xaeb\xec\xe9\x8c\xce?\xf0\xd5@\xcb\x1a\xa8\x152\xc1\x05\xcf\x0b\xc1\x82>6\xb0`\xac\x04\xec\xa5KFz\\\x19\xb3\x02\xb6}Dz"\xe9;]\xc2\x1e\xc5\xcf=\x04]\xabE\xaa\xde3v\xaf\xe1\xd0Xyh\xacLG\x0d\xbd\xbeI\xddb\xe7A\x1e/\x83/+\xe7\xae\x0e\xa1\xd7m\xb0JB\x8f\xbdP\xfe\x0adk\xe7\xaf vCX\x9c\x91\xe9\x0d\xa3$\x8c7', _namespace)
    dc.install_model(GeneratedSchemaN1, _jsoncompat_init_2, b'x\xda\x85PA\x0e\x83 \x10\xbc\xfb\x0aC{\xd4\x82x\xf3\x0d\xfd\x84\xad\x8b\xdaD \xcb^\x1a\xe3\xdf\x8b-!\x98X=\xc1\xceLfgv\xce\xf2\x9c];P\x8e5\xf9\xec\x07?j\x11\xff+\x89\xa0\xfc\xcc.\xfc+\xe3\xbabE\xe4\xdcs\x80\xa9]\xe9\x81\xc8\xba\x86\xf3\x973\xba\xfc\xc17\x83=\xef\xb0U\xc4\xa5\x90\xa2\xac$\x0f\xfah`\xd1X@\x1a\xc1%+=\xae\x8c\xd9\x00\xfb9"\xbdd\xe9\xbb\x14\xa1Gu\xd8C\xb2\xadZ\xa6\xea\x7f\xc1\x1e-\x9e\x06\xabO\x83\xd5\xe9\xaai\xd4w\xd0=\x0d\x1e\x14\xf12\xf4\xb6\xb0\xba:\xc2Q\xf7!j\x16<v\xcb,\x1f\xb5\xd7h\xcb', _namespace)
    dc.install_model(GeneratedSchemaN2, _jsoncompat_init_3, b'x\xda\x85\x90A\x0e\x83 \x10E\xf7\x9c\xc2\xd0.\xb5 \xee<C/a+\xa8M\x042\xcc\xa61\xde\xbdh\x09\xc1F\xeb\x0a\xe6\xff\x9f\xcf\x1b&\x92e\xf4\xdaJ\xe5h\x9dM~\xf0\xa3\xe6\xf1\xbe\x98 \x95\x9f\xe9\x85\xad1\xa6K\x9aG\xcf={96\x8b\xdd#ZW3\xf6rF\x17_\xf9f\xa0c-4\x0a\x99\xe0\x82\x17\xa5`!\x1f\x0b,\x18+\x01\x07\xe9\x92\'\xbd\xae\x8c\xd9\x08\xfb\x1c\xd1\x9eIz\xcey\xd8\xa3\xfc\xbb\x87\xa0\xdb\xb4H\xd3G`\x8f\x06N\xc1\xaaS\xb0*}j\x1c\xf4]\xea\x0e{/\xf2\xf83\xf8\xb6riu\x08\x83\xee\x02*\x09\x1d{x?h\x87Xk\x09\x99?Bas\xa2', _namespace)
    dc.install_model(GeneratedSchemaN3, _jsoncompat_init_4, b'x\xda\xab\xe6RPP\xca\xcd\xcc\xf3I\xcdK/\xc9P\xb2R0\xd0\x01\x89\x94T\x16\xa4\x029J\xc5%E\x99y\xe9J\\\xb5\x00\xe4\xcb\x0br', _namespace)
    dc.bind_module(1, [(GeneratedSchema, 0), (GeneratedSchemaN0, 1), (GeneratedSchemaN1, 2), (GeneratedSchemaN2, 3), (GeneratedSchemaN3, 5)], [
        ('root', GeneratedSchema, 1, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"ref":2},{"object":{"properties":[["foo",6]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",4]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":5}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"ref":2}]}],"patterns":[]}'),
        ('root', GeneratedSchemaN0, 2, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1},{"object":{"properties":[["foo",5]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",3]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":4}]},{"types":["string"],"choices":null,"rules":[]},{"types":null,"choices":null,"rules":[{"ref":1}]}],"patterns":[]}'),
        ('root', GeneratedSchemaN1, 3, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"ref":1}]},{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",2]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":3}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ('root', GeneratedSchemaN2, 4, b'{"version":3,"nodes":[{"types":null,"choices":null,"rules":[{"object":{"properties":[["bar",1]],"patterns":[],"required":[],"additional":null}}]},{"types":null,"choices":null,"rules":[{"ref":2}]},{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("any",),
        ('root', GeneratedSchemaN3, 6, b'{"version":3,"nodes":[{"types":["string"],"choices":null,"rules":[]}],"patterns":[]}'),
        ("str",)
    ], b'{"version":4,"base_nodes":7,"guard_nodes":[],"guards":[],"conversion_validates":[false,false,false,false,false,true,false],"json_keys":[]}')


_jsoncompat_bind((GeneratedSchema, GeneratedSchemaN0, GeneratedSchemaN1, GeneratedSchemaN2, GeneratedSchemaN3,), globals())
